Repository toptal/picasso, pull requests merged in 2021-06, with the labels that each got.

#2095 feat: add `final-forms` exports
  packages/picasso-forms/src/index.ts
Labels: Chore, no-jira

#2097 fix(picasso): pin d3-array version
  packages/picasso/package.json
Labels: no-jira

#2099 feat(drawer): add new types to the Drawer
  packages/picasso-lab/src/Drawer/Drawer.tsx
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-custom-title-effect-1-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-default-effect-1-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-effect-1-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-effect-2-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-effect-3-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-effect-4-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-effect-5-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-width-snap.png
  packages/picasso-lab/src/Drawer/__image_snapshots__/drawer-without-title-effect-1-snap.png
  packages/picasso-lab/src/Drawer/story/Widths.example.tsx
  packages/picasso-lab/src/Drawer/story/index.jsx
  packages/picasso-lab/src/Drawer/styles.ts
Labels: BREAKING CHANGE

#2101 fix(picasso-forms): validation on submit
  packages/picasso-forms/src/Form/Form.tsx
  packages/picasso-forms/src/FormConfig/test.tsx
Labels: Bugfix, no-jira

#2100 style(Modal): fix modal content overflow issue
  packages/picasso/src/ModalContent/styles.ts
  packages/picasso/src/TreeView/__image_snapshots__/treeview-with-modal-effect-1-snap.png
Labels: Bugfix

#2102 feat(tooltip): show tooltip on both label and control
  cypress/component/Tooltip.spec.tsx
  packages/picasso/src/Checkbox/Checkbox.tsx
  packages/picasso/src/FormControlLabel/FormControlLabel.tsx
  packages/picasso/src/Radio/Radio.tsx
Labels: Bugfix

#2105 fix(TagSelector): add definition of popperContainer prop
  packages/picasso/src/TagSelector/TagSelector.tsx
Labels: no-jira

#2106 feat(Section): [FX-1985] Add bordered variant
  cypress/component/Section.spec.tsx
  packages/picasso-lab/src/Section/Section.tsx
  packages/picasso-lab/src/Section/story/Variant.example.tsx
  packages/picasso-lab/src/Section/story/index.jsx
  packages/picasso-lab/src/Section/styles.ts
Labels: Feature

#2107 feat(Icon): add pin solid icon
  packages/picasso/src/Icon/PinSolid16.tsx
  packages/picasso/src/Icon/PinSolid24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/pinSolid16.svg
  packages/picasso/src/Icon/svg/pinSolid24.svg
Labels: icon
