Repository toptal/picasso, pull requests merged in 2021-11, with the labels that each got.

#2201 refactor(Container): make gap to fuction as other size props
  cypress/component/Badge.spec.tsx
  cypress/component/Tag.spec.tsx
  packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
  packages/picasso/src/ButtonSplit/story/Sizes.example.tsx
  packages/picasso/src/ButtonSplit/story/Variants.example.tsx
  packages/picasso/src/Container/Container.tsx
  packages/picasso/src/Container/styles.ts
  packages/picasso/src/Select/story/Disabled.example.tsx
  packages/picasso/src/Tag/story/Checkable.example.tsx
  packages/picasso/src/Tag/story/Default.example.tsx
  packages/picasso/src/Tag/story/Variants.example.tsx
  packages/picasso/src/TagRectangular/story/Variants.example.tsx
Labels: no-jira

#2202 refactor(Avatar): make avatar more reusable
  packages/picasso/src/AccountSelect/__snapshots__/test.tsx.snap
  packages/picasso/src/Avatar/Avatar.tsx
  packages/picasso/src/Avatar/AvatarWrapper/AvatarWrapper.tsx
  packages/picasso/src/Avatar/AvatarWrapper/styles.ts
  packages/picasso/src/Avatar/IconAvatar.tsx
  packages/picasso/src/Avatar/IconAvatar/IconAvatar.tsx
  packages/picasso/src/Avatar/IconAvatar/styles.ts
  packages/picasso/src/Avatar/ImageAvatar.tsx
  packages/picasso/src/Avatar/ImageAvatar/ImageAvatar.tsx
  packages/picasso/src/Avatar/ImageAvatar/styles.ts
  packages/picasso/src/Avatar/ImagePlaceholder.tsx
  packages/picasso/src/Avatar/InitialsAvatar.tsx
  packages/picasso/src/Avatar/TextAvatar/TextAvatar.tsx
  packages/picasso/src/Avatar/TextAvatar/styles.ts
  packages/picasso/src/Avatar/__snapshots__/test.tsx.snap
  packages/picasso/src/Avatar/story/Default.example.tsx
  packages/picasso/src/Avatar/styles.ts
  packages/picasso/src/Avatar/test.tsx
  packages/picasso/src/Avatar/utils/getClipPathCornerMask.ts
  packages/picasso/src/Avatar/utils/getDimensions.ts
  packages/picasso/src/OverlayBadge/__image_snapshots__/overlaybadge-sizes-snap.png
  packages/picasso/src/Page/__image_snapshots__/page-default-snap.png
  packages/picasso/src/Page/__image_snapshots__/page-full-width-snap.png
  packages/picasso/src/Page/__image_snapshots__/page-wide-width-snap.png
  packages/picasso/src/Page/__image_snapshots__/page-with-banner-snap.png
  packages/picasso/src/Page/__image_snapshots__/page-with-compound-banner-snap.png
  packages/picasso/src/PageTopBar/__image_snapshots__/page-topbar-extra-header-menu-content-snap.png
  packages/picasso/src/PageTopBar/__image_snapshots__/page-topbar-right-content-snap.png
  packages/picasso/src/PageTopBarMenu/__snapshots__/test.tsx.snap
  packages/picasso/src/UserBadge/__image_snapshots__/userbadge-custom-snap.png
  packages/picasso/src/UserBadge/__image_snapshots__/userbadge-sizes-snap.png
  packages/picasso/src/UserBadge/__snapshots__/test.tsx.snap
Labels: no-jira

#2224 chore: set access so public
  .changeset/config.json
Labels: no-jira

#2225 Version Packages
  .changeset/perfect-cobras-search.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2217 fix: updated generate-icons script with .prettierrc.js config
  .changeset/famous-melons-check.md
  bin/generate-icons
  packages/picasso/src/Icon/Dialpad16.tsx
Labels: no-jira

#2228 chore: set publish directory
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2227 Version Packages
  .changeset/brown-monkeys-worry.md
  .changeset/famous-melons-check.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2229 chore: fix directory path in publishConfig
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2231 chore: fix path to prepublish.js
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2214 fix: revert adding postfix to input
  .changeset/wild-gorillas-shave.md
  packages/picasso-forms/src/Input/Input.tsx
  packages/picasso-forms/src/Input/utils/get-input-name.test.ts
  packages/picasso-forms/src/Input/utils/get-input-name.ts
Labels: no-jira

#2240 chore: fix release through changesets
  bin/prepublish.js
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2239 Version Packages
  .changeset/wild-gorillas-shave.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2244 Version Packages
  .changeset/angry-steaks-worry.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2245 Version Packages
  .changeset/dull-avocados-chew.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2235 feat(icon): add support icon
  .changeset/olive-turtles-wash.md
  packages/picasso/src/Icon/Support16.tsx
  packages/picasso/src/Icon/Support24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/support16.svg
  packages/picasso/src/Icon/svg/support24.svg
Labels: icon

#2236 feat(icon): add new icon
  .changeset/khaki-readers-behave.md
  packages/picasso/src/Icon/New16.tsx
  packages/picasso/src/Icon/New24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/new16.svg
  packages/picasso/src/Icon/svg/new24.svg
Labels: icon

#2243 chore: update jenkins_url
  .github/workflows/release.yml
Labels: no-jira

#2246 Version Packages
  .changeset/dirty-zoos-punch.md
  .changeset/khaki-readers-behave.md
  .changeset/olive-turtles-wash.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#2248 chore(release): trigger build image pipeline
  .github/workflows/release.yml
Labels: no-jira

#2234 feat(Link): [FX-2253] update link according to spec
  .changeset/proud-files-dream.md
  cypress/component/Link.spec.tsx
  cypress/component/Tooltip.spec.tsx
  packages/picasso/src/AccountSelect/AccountSelect.tsx
  packages/picasso/src/AccountSelect/__snapshots__/test.tsx.snap
  packages/picasso/src/Button/story/Augmentation.example.tsx
  packages/picasso/src/Link/Link.tsx
  packages/picasso/src/Link/__snapshots__/test.tsx.snap
  packages/picasso/src/Link/story/Color.example.tsx
  packages/picasso/src/Link/story/index.jsx
  packages/picasso/src/Link/styles.ts
  packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap
  packages/picasso/src/UserBadge/__image_snapshots__/userbadge-custom-name-rendering-snap.png
  packages/picasso/src/UserBadge/__image_snapshots__/userbadge-with-title-snap.png
  packages/picasso/src/UserBadge/story/CustomName.example.tsx
  packages/picasso/src/UserBadge/story/index.jsx
Labels: Feature

#2252 Version Packages
  .changeset/proud-files-dream.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2253 fix: job_params needs to be in JSON format
  .github/workflows/release.yml
Labels: no-jira

#2241 chore: disable GHA for changesets PR
  .github/workflows/pr.yaml
  .github/workflows/release.yml
  .github/workflows/visual-testing.yml
  ci/jobs/picasso-pr-specs/Jenkinsfile
Labels: no-jira

#2258 Version Packages [skip ci]
  .changeset/tame-squids-buy.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2259 chore: set correct 'jenkins_user'
  .github/workflows/release.yml
Labels: no-jira

#2263 Version Packages [skip ci]
  .changeset/new-items-bake.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2266 Version Packages [skip ci]
  .changeset/selfish-buttons-cover.md
  .changeset/tidy-impalas-suffer.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2273 Version Packages [skip ci]
  .changeset/odd-guests-explain.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2279 chore: remove the dist-package/dist-package
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2260 fix(DatePicker): normalize min/max dates before comparison
  .changeset/fast-plums-try.md
  packages/picasso-lab/src/DatePicker/DatePicker.tsx
  packages/picasso-lab/src/DatePicker/test.tsx
  packages/picasso-lab/src/DatePicker/utils.ts
Labels: Bugfix

#2278 chore: trigger jenkins build job from GHA
  .github/workflows/release.yml
Labels: no-jira

#2274 Version Packages [skip ci]
  .changeset/dirty-months-float.md
  .changeset/fast-plums-try.md
  .changeset/orange-kids-approve.md
  .changeset/popular-ads-drop.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: DO NOT MERGE, no-jira

#2287 Version Packages [skip ci]
  .changeset/spicy-hats-try.md
  .changeset/tough-laws-pull.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2290 feat(icon): add flash24 icon
  .changeset/nice-mugs-press.md
  packages/picasso/src/Icon/Flash24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/flash24.svg
Labels: icon

#2291 Version Packages [skip ci]
  .changeset/empty-gorillas-walk.md
  .changeset/nice-mugs-press.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2296 Version Packages [skip ci]
  .changeset/plenty-impalas-return.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
