Repository toptal/picasso, pull requests merged in 2021-09, with the labels that each got.

#2147 fix(Section): removes header padding when collapsed
  packages/picasso-lab/src/Section/Section.tsx
  packages/picasso-lab/src/Section/__snapshots__/test.tsx.snap
  packages/picasso-lab/src/Section/styles.ts
Labels: no-jira

#2152 fix: [SPT-1892] updated TypographyOverflow click event for tooltip
  packages/picasso-lab/src/TypographyOverflow/TypographyOverflow.tsx
Labels: Bugfix

#2154 fix: [SPT-1889] updated modal scrollable shades to fix resize inheritance
  packages/picasso/src/ModalContent/use-scrollable-shades.ts
Labels: Bugfix

#2145 chore(deps-dev): [Security] Resolve lodash to 4.17.21
  package.json
  yarn.lock
Labels: no-jira

#2161 fix(picasso): add explicit dependency on debounce
  packages/picasso-charts/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso/package.json
  yarn.lock
Labels: no-jira

#2153 feat: add maxSearchItems for Form.Select
  packages/picasso/src/NativeSelect/NativeSelect.tsx
  packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
  packages/picasso/src/NonNativeSelect/test.tsx
  packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
  packages/picasso/src/NonNativeSelectOptions/styles.ts
  packages/picasso/src/ScrollMenu/ScrollMenu.tsx
  packages/picasso/src/Select/Select.tsx
  packages/picasso/src/Select/hooks/use-select-state/test.ts
  packages/picasso/src/Select/hooks/use-select-state/use-select-state.ts
  packages/picasso/src/Select/story/Limit.example.tsx
  packages/picasso/src/Select/story/SearchBehavior.example.tsx
  packages/picasso/src/Select/story/index.jsx
  packages/picasso/src/Select/types.ts
  packages/picasso/src/Select/utils/constants.ts
Labels: Feature

#2165 fix: remove material-ui/styles dependency
  package.json
  packages/picasso-provider/package.json
  packages/picasso-provider/src/Picasso/Picasso.tsx
  packages/picasso/package.json
  packages/picasso/src/Link/Link.tsx
  yarn.lock
Labels: Bugfix, no-jira

#2159 chore: simplify types for components with static properties
  packages/picasso-lab/src/Note/Note.tsx
  packages/picasso/src/Accordion/Accordion.tsx
  packages/picasso/src/Alert/Alert.tsx
  packages/picasso/src/Badge/Badge.tsx
  packages/picasso/src/Breadcrumbs/Breadcrumbs.tsx
  packages/picasso/src/Button/Button.tsx
  packages/picasso/src/Checkbox/Checkbox.tsx
  packages/picasso/src/Dropdown/Dropdown.tsx
  packages/picasso/src/Form/Form.tsx
  packages/picasso/src/Grid/Grid.tsx
  packages/picasso/src/Helpbox/Helpbox.tsx
  packages/picasso/src/Menu/Menu.tsx
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/Notification/Notification.tsx
  packages/picasso/src/OverlayBadge/OverlayBadge.tsx
  packages/picasso/src/Page/Page.tsx
  packages/picasso/src/PageBanner/PageBanner.tsx
  packages/picasso/src/PageHead/PageHead.tsx
  packages/picasso/src/Radio/Radio.tsx
  packages/picasso/src/Sidebar/Sidebar.tsx
  packages/picasso/src/Table/Table.tsx
  packages/picasso/src/Tabs/Tabs.tsx
  packages/picasso/src/Tag/Tag.tsx
  packages/picasso/src/TagSelector/TagSelector.tsx
  packages/shared/src/types.ts
Labels: no-jira

#2167 fix(Autocomplete): do not render noOptions item when no options available
  packages/picasso/src/Autocomplete/Autocomplete.tsx
  packages/picasso/src/Autocomplete/test.tsx
Labels: Feature

#2172 feat: add possibility to pass data-testid for picasso-forms Form
  packages/picasso-forms/src/Form/Form.tsx
Labels: Chore

#2171 fix: scroll to error while Form is rerendered
  cypress/component/Form.spec.tsx
  cypress/support/commands.js
  cypress/support/index.js
  packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
Labels: Bugfix

#2177 feat(Icon): [SPB-2461] add transfer icon
  packages/picasso-charts/package.json
  packages/picasso-forms/package.json
  packages/picasso-lab/package.json
  packages/picasso/package.json
  packages/picasso/src/Icon/Transfer16.tsx
  packages/picasso/src/Icon/Transfer24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/transfer16.svg
  packages/picasso/src/Icon/svg/transfer24.svg
Labels: Feature
