Repository toptal/picasso, pull requests merged in 2021-08, with the labels that each got.

#2124 feat(Dropdown): add contentOverflow option
  cypress/component/Dropdown.spec.tsx
  packages/picasso/src/Dropdown/Dropdown.tsx
  packages/picasso/src/Dropdown/story/LongMenuList.example.tsx
  packages/picasso/src/Dropdown/story/index.jsx
  packages/picasso/src/Dropdown/styles.ts
  yarn.lock
Labels: Feature

#2134 fix: failing master-release job when docs not deployed
  ci/jobs/picasso-master-release/Jenkinsfile
Labels: no-jira

#2140 docs: add info about designing component API
  .storybook/stories/contribution/story/index.tsx
  .storybook/stories/picasso/story/index.tsx
  CONTRIBUTING.md
  docs/api-principles.md
  docs/contribution/component-api.md
Labels: docs

#2146 chore: run tests on PRs to feature/* branches
  .github/workflows/pr.yaml
Labels: no-jira
