Repository toptal/picasso, pull requests merged in 2021-12, with the labels that each got.

#2299 Version Packages [skip ci]
  .changeset/violet-llamas-peel.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2298 feat(DatePicker): added ability to pass custom parsers for DatePicker's Input
  .changeset/mean-plants-bathe.md
  cypress/component/DatePicker.spec.tsx
  packages/picasso-lab/src/DatePicker/DatePicker.tsx
  packages/picasso-lab/src/DatePicker/index.ts
  packages/picasso-lab/src/DatePicker/story/AllowCustomValue.example.tsx
  packages/picasso-lab/src/DatePicker/story/WithInputCustomValueParser.example.tsx
  packages/picasso-lab/src/DatePicker/story/index.jsx
  packages/picasso-lab/src/DatePicker/test.tsx
  packages/picasso-lab/src/DatePicker/types.ts
  packages/picasso-lab/src/DatePicker/utils.ts
  packages/picasso-lab/src/index.ts
Labels: Feature, BREAKING CHANGE

#2303 Version Packages [skip ci]
  .changeset/afraid-garlics-play.md
  .changeset/mean-plants-bathe.md
  .changeset/weak-pianos-drive.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2307 Version Packages [skip ci]
  .changeset/witty-beds-do.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2306 chore(Button): add forwardRef to Augmentation example
  packages/picasso/src/Button/story/Augmentation.example.tsx
Labels: no-jira

#2311 Version Packages [skip ci]
  .changeset/neat-glasses-compete.md
  .changeset/plenty-lions-jump.md
  .changeset/short-onions-cheer.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2313 Version Packages [skip ci]
  .changeset/curvy-peas-confess.md
  .changeset/thirty-ties-bake.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2320 Version Packages [skip ci]
  .changeset/kind-donkeys-think.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2323 Version Packages [skip ci]
  .changeset/hot-sheep-exist.md
  .changeset/smooth-melons-collect.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2327 Version Packages [skip ci]
  .changeset/chatty-candles-learn.md
  .changeset/chilled-gifts-reply.md
  .changeset/modern-beans-dance.md
  .changeset/shaggy-turtles-tap.md
  .changeset/tall-penguins-remember.md
  .changeset/young-lemons-kneel.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: DO NOT MERGE, no-jira

#2333 chore: added container-borders codemod to README
  packages/picasso-codemod/README.md
Labels: no-jira

#2324 feat(Forms): add ability to disable auto-focus and auto-scroll on Form submission error
  .changeset/curly-apricots-tease.md
  packages/picasso-forms/src/Form/Form.tsx
  packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap
  packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/Form/test.tsx
  packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
  packages/picasso-forms/src/utils/scroll-to.ts
Labels: Bugfix

#2335 Version Packages [skip ci]
  .changeset/curly-apricots-tease.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2332 chore: notify jira about contribution
  .github/workflows/notify-jira-about-contribution.yml
Labels: no-jira

#2336 fix(TreeView): fix PointLink positioning to avoid unexpected 0.5px shifts
  .changeset/modern-mice-destroy.md
  packages/picasso/src/StaticTreeView/__image_snapshots__/statictreeview-compact-tree-snap.png
  packages/picasso/src/StaticTreeView/__image_snapshots__/statictreeview-horizontal-direction-snap.png
  packages/picasso/src/TreeView/PointLink/PointLink.tsx
Labels: no-jira

#2337 Version Packages [skip ci]
  .changeset/modern-mice-destroy.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2342 Version Packages [skip ci]
  .changeset/swift-badgers-appear.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2341 fix: patch codemod typography-sizes for picasso v17
  .changeset/thirty-bottles-complain.md
  packages/picasso-codemod/src/v17.0.0/typography-sizes/__testfixtures__/basic.input.tsx
  packages/picasso-codemod/src/v17.0.0/typography-sizes/__testfixtures__/basic.output.tsx
  packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
Labels: no-jira

#2343 Version Packages [skip ci]
  .changeset/thirty-bottles-complain.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
Labels: no-jira

#2340 fix(Popper): fixed Popper overflow inside Modal
  .changeset/late-insects-jog.md
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/Modal/ModalContext.ts
  packages/picasso/src/Popper/Popper.tsx
Labels: Bugfix, Chore

#2346 chore(picasso-forms): add additional reexports from final-form packages
  .changeset/heavy-peaches-pay.md
  packages/picasso-forms/src/index.ts
Labels: Chore

#2349 chore: greet contributor
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/handle-contribution.yml
  .github/workflows/notify-jira-about-contribution.yml
Labels: no-jira

#2344 Version Packages [skip ci]
  .changeset/heavy-peaches-pay.md
  .changeset/hot-humans-reflect.md
  .changeset/late-insects-jog.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2351 fix(List): add font-size to List root to fix bullets alignment
  .changeset/witty-brooms-sin.md
  cypress/component/List.spec.tsx
  packages/picasso/src/List/styles.ts
Labels: no-jira

#2355 chore: enable fast refresh
  .storybook/main.js
Labels: no-jira

#2354 Version Packages [skip ci]
  .changeset/witty-brooms-sin.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2356 chore(picasso): change key press focus logic for Select component
  .changeset/small-seahorses-speak.md
  packages/picasso/src/Select/hooks/use-select-props/use-select-keydown-handler/test.ts
  packages/picasso/src/Select/hooks/use-select-props/use-select-keydown-handler/use-select-keydown-handler.ts
Labels: Feature

#2360 chore: fix typecheck for fixtures
  .prettierignore
  .storybook/main.js
  .storybook/tsconfig.json
  packages/picasso-codemod/src/v17.0.0/container-borders/__testfixtures__/actual.tsx
  packages/picasso-codemod/src/v17.0.0/container-borders/__testfixtures__/expected.tsx
  packages/picasso-forms/src/Form/test.tsx
  packages/picasso-provider/src/Picasso/story/index.jsx
Labels: no-jira

#2359 Version Packages [skip ci]
  .changeset/small-seahorses-speak.md
  .changeset/thick-tigers-search.md
  packages/picasso-lab/CHANGELOG.md
  packages/picasso-lab/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2361 chore: add changeset guidelines
  CONTRIBUTING.md
  docs/contribution/changeset-guidelines.md
Labels: no-jira
