Repository toptal/picasso, pull requests merged in 2021-05, with the labels that each got.

#2062 chore: restructure code owners
  .github/CODEOWNERS
  .github/workflows/request-review-on-pr.yml
Labels: no-jira

#2059 feat(Icon): add asterisk solid icon
  packages/picasso/src/Icon/AsteriskSolid16.tsx
  packages/picasso/src/Icon/AsteriskSolid24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/asteriskSolid16.svg
  packages/picasso/src/Icon/svg/asteriskSolid24.svg
Labels: icon

#2063 feat(ProgressBar): [TEA-2569] Introduce ProgressBar component
  cypress/component/ProgressBar.spec.tsx
  packages/picasso-lab/src/ProgressBar/ProgressBar.tsx
  packages/picasso-lab/src/ProgressBar/__snapshots__/test.tsx.snap
  packages/picasso-lab/src/ProgressBar/index.ts
  packages/picasso-lab/src/ProgressBar/story/AnimatingProgressChange.example.tsx
  packages/picasso-lab/src/ProgressBar/story/Default.example.tsx
  packages/picasso-lab/src/ProgressBar/story/WithPercentage.example.tsx
  packages/picasso-lab/src/ProgressBar/story/index.jsx
  packages/picasso-lab/src/ProgressBar/styles.ts
  packages/picasso-lab/src/ProgressBar/test.tsx
  packages/picasso-lab/src/index.ts
Labels: Feature, New component

#2066 fix(list): render ListItem as div to avoid nested paragraph warning
  packages/picasso-lab/src/ListItem/ListItem.tsx
Labels: no-jira

#2068 feat(shared): [SPB-1999] export used helpers
  .prettierignore
  packages/picasso/src/Grid/index.ts
  packages/picasso/src/index.ts
  packages/picasso/src/utils/index.ts
Labels: Chore, Feature

#2069 fix: reappearing tooltip after moving mouse within boundaries of triggered button
  cypress/component/Tooltip.spec.tsx
  cypress/support/index.js
  cypress/tsconfig.json
  package.json
  packages/picasso/src/Tooltip/Tooltip.tsx
  yarn.lock
Labels: Bugfix

#2072 fix(modal): the content is not scrollable on mobile
  packages/picasso/src/Modal/styles.ts
Labels: Bugfix

#2075 fix(Modal): fix width and height of top aligned modal on small screens
  packages/picasso/src/Modal/styles.ts
Labels: Bugfix

#2085 fix: move dependencies to picasso from lab
  packages/picasso-lab/package.json
  packages/picasso/package.json
  packages/picasso/src/Alert/story/index.jsx
  packages/picasso/src/Badge/story/index.jsx
  packages/picasso/src/Breadcrumbs/story/index.jsx
  packages/picasso/src/List/story/index.jsx
  packages/picasso/src/OverlayBadge/story/index.jsx
  packages/picasso/src/PageHead/story/index.jsx
  packages/picasso/src/ProgressBar/story/index.jsx
  packages/picasso/src/Quote/story/index.jsx
  packages/picasso/src/Rating/story/index.jsx
  packages/picasso/src/SkeletonLoader/story/index.jsx
  packages/picasso/src/Switch/story/index.jsx
  packages/picasso/src/TimePicker/story/index.jsx
  packages/picasso/src/TreeView/TreeViewContainer.tsx
  packages/picasso/src/TreeView/story/index.jsx
  yarn.lock
Labels: no-jira

#2086 feat(forms): export additional types from final-form
  packages/picasso-forms/src/index.ts
Labels: no-jira

#2090 chore: fix review pr workflow
  .github/workflows/request-review-on-pr.yml
Labels: no-jira

#2048 feat(Tag): add styles for tag content overflow
  cypress/component/Tag.spec.tsx
  packages/picasso/src/Tag/story/index.jsx
  packages/picasso/src/Tag/styles.ts
Labels: no-jira
