Repository toptal/picasso, pull requests merged in 2021-07, with the labels that each got.

#2109 feat: add final-form exports
  packages/picasso-forms/src/index.ts
Labels: Chore

#2111 fix(OutlinedInput): do not trigger onBlur event after clicking adornment
  packages/picasso/src/OutlinedInput/OutlinedInput.tsx
Labels: no-jira

#2113 fix(Select): close Popper after disabling Select
  packages/picasso/src/Select/hooks/use-select-state/test.ts
  packages/picasso/src/Select/hooks/use-select-state/use-select-state.ts
Labels: no-jira

#2115 fix(TagSelector): compare by value
  cypress/component/TagSelector.spec.tsx
  packages/picasso/src/TagSelector/TagSelector.tsx
  packages/picasso/src/TagSelector/test.tsx
Labels: Bugfix

#2117 chore(Autocomplete): implement a disabled state of autocomplete
  cypress/component/Autocomplete.spec.tsx
  packages/picasso/src/Autocomplete/Autocomplete.tsx
  packages/picasso/src/Autocomplete/story/Disabled.example.tsx
  packages/picasso/src/Autocomplete/story/index.jsx
  packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts
Labels: no-jira

#2121 feat: change separator color in `OverviewBlock` component
  packages/picasso-lab/src/OverviewBlock/__image_snapshots__/overviewblock-default-snap.png
  packages/picasso-lab/src/OverviewBlock/__image_snapshots__/overviewblock-multi-line-snap.png
  packages/picasso-lab/src/OverviewBlock/__image_snapshots__/overviewblock-number-snap.png
  packages/picasso-lab/src/OverviewBlock/__image_snapshots__/overviewblock-routing-snap.png
  packages/picasso-lab/src/OverviewBlock/__image_snapshots__/overviewblock-text-snap.png
  packages/picasso-lab/src/OverviewBlock/styles.ts
  packages/picasso-lab/src/OverviewBlockGroup/__image_snapshots__/visual-variants-of-the-groups-block-width-snap.png
  packages/picasso-lab/src/OverviewBlockGroup/__image_snapshots__/visual-variants-of-the-groups-center-aligned-snap.png
Labels: Feature
