Repository toptal/picasso, pull requests merged in 2022-10, with the labels that each got.

#3125 chore(Switch): add type for switch field
  .changeset/proud-bobcats-hunt.md
  packages/picasso-forms/src/Field/Field.tsx
  packages/picasso-forms/src/Switch/Switch.tsx
  packages/picasso/src/Switch/Switch.tsx
Labels: Bugfix

#3126 Version Packages
  .changeset/proud-bobcats-hunt.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3130 feat(PageHead): add noBorder prop
  .changeset/hungry-clouds-stare.md
  packages/picasso/src/PageHead/PageHead.tsx
  packages/picasso/src/PageHead/story/NoBorder.example.tsx
  packages/picasso/src/PageHead/story/index.jsx
  packages/picasso/src/PageHead/styles.ts
Labels: no-jira

#3131 Version Packages
  .changeset/hungry-clouds-stare.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3114 fix: fix contributing markdown file
  CONTRIBUTING.md
Labels: no-jira

#3133 Version Packages
  .changeset/loud-moles-attack.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3134 fix(AvatarUpload): remove redundant time unit for animation function
  .changeset/calm-pots-play.md
  packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
Labels: contribution

#3135 Version Packages
  .changeset/calm-pots-play.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3139 Version Packages
  .changeset/nervous-goats-hunt.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3148 Version Packages
  .changeset/breezy-rules-mate.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3137 feat(picasso): adopt picasso packages for react@18 strict mode
  .changeset/giant-crews-peel.md
  .changeset/silly-avocados-enjoy.md
  .storybook/stories/tutorials/server-side-rendering/story/index.jsx
  packages/picasso-provider/package.json
  packages/picasso-provider/src/Favicon/Favicon.tsx
  packages/picasso-provider/src/Favicon/__snapshots__/test.tsx.snap
  packages/picasso-provider/src/Picasso/FixViewport.tsx
  packages/picasso-provider/src/Picasso/HelmetProvider/HelmetProvider.tsx
  packages/picasso-provider/src/Picasso/HelmetProvider/index.ts
  packages/picasso-provider/src/Picasso/Picasso.tsx
  packages/picasso/package.json
  packages/picasso/src/PageHelmet/PageHelmet.tsx
  packages/picasso/src/PageHelmet/story/index.jsx
  yarn.lock
Labels: contribution

#3151 Version Packages
  .changeset/giant-crews-peel.md
  .changeset/silly-avocados-enjoy.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3144 feat: decimal point options
  .changeset/gentle-meals-sort.md
  packages/picasso/src/utils/Formatters/format-amount.ts
  packages/picasso/src/utils/Formatters/story/amount.example.tsx
  packages/picasso/src/utils/Formatters/test.ts
Labels: contribution

#3154 Version Packages
  .changeset/brave-hounds-travel.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3155 Version Packages
  .changeset/purple-hotels-behave.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3157 chore: duplicate image to artifact registry for later replace
  ci/jobs/build-image/Jenkinsfile
Labels: contribution

#3158 feat: add options prop
  .changeset/fuzzy-items-invite.md
  packages/picasso/src/Amount/Amount.tsx
  packages/picasso/src/Amount/story/Decimals.example.tsx
  packages/picasso/src/Amount/story/index.jsx
Labels: contribution

#3163 Version Packages
  .changeset/fuzzy-items-invite.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3162 fix(CheckboxGroup): fix value type for form usage
  .changeset/breezy-singers-compare.md
  cypress/component/Form.spec.tsx
  packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso/src/Checkbox/Checkbox.tsx
Labels: Bugfix

#3165 Version Packages
  .changeset/breezy-singers-compare.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3167 Version Packages
  .changeset/sixty-games-watch.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3174 chore(deps): bump minimatch to fixed version
  package.json
  yarn.lock
Labels: dependencies, no-jira

#3175 Version Packages
  .changeset/loud-scissors-remember.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3176 Version Packages
  .changeset/slow-spies-refuse.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3177 fix: fix docker image build job
  ci/jobs/build-image/Jenkinsfile
Labels: no-jira, contribution

#3181 Version Packages
  .changeset/sixty-lobsters-shave.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3184 Version Packages
  .changeset/olive-beers-sleep.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#3182 feat(DatePicker): add footer background color
  .changeset/eleven-drinks-speak.md
  packages/picasso/src/DatePicker/DatePicker.tsx
  packages/picasso/src/DatePicker/story/WithFooterBackgroundColor.example.tsx
  packages/picasso/src/DatePicker/story/index.jsx
  packages/picasso/src/DatePicker/test.tsx
Labels: contribution

#3185 Version Packages
  .changeset/eleven-drinks-speak.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3188 chore: fix scroll to anchor in storybook
  .storybook/addons/anchor-link-handler/index.js
Labels: no-jira

#3194 Version Packages
  .changeset/old-pandas-tie.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
