Repository toptal/picasso, pull requests merged in 2022-06, with the labels that each got.

#2836 chore: skip stories with animations for happo storybook
  packages/picasso-charts/src/BarChart/story/index.jsx
  packages/topkit-analytics-charts/src/CategoriesChart/story/index.jsx
Labels: no-jira

#2840 fix(Notification): fix notification overflow on small screens
  .changeset/large-badgers-remain.md
  .changeset/shiny-beans-exist.md
  .changeset/wicked-cycles-kneel.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/picasso/src/utils/Notifications/styles.ts
  packages/shared/package.json
  yarn.lock
Labels: contribution

#2844 Version Packages [skip ci]
  .changeset/large-badgers-remain.md
  .changeset/shiny-beans-exist.md
  .changeset/wicked-cycles-kneel.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#2845 Version Packages [skip ci]
  .changeset/eleven-eels-tie.md
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2848 chore: remove remaining CI job and mention
  ci/jobs/picasso-pr-specs/Jenkinsfile
  docs/contribution/pr_jobs.md
Labels: no-jira

#2849 fix(Select): forward ref properly
  .changeset/ninety-ligers-scream.md
  packages/picasso/src/Select/Select.tsx
  packages/picasso/src/utils/forward-ref.ts
Labels: no-jira, contribution

#2852 feat: allow injecting Picasso styles first
  .changeset/polite-kiwis-rush.md
  packages/picasso-provider/src/Picasso/Picasso.tsx
Labels: contribution

#2850 chore(happo): disable flaky snapshot
  .storybook/stories/tutorials/layout/story/index.jsx
  packages/picasso-provider/src/Picasso/story/index.jsx
Labels: WIP, no-jira

#2863 chore(BarChart): simplify unit and cypress tests
  cypress/component/BarChart.spec.tsx
  packages/picasso-charts/src/BarChart/__image_snapshots__/barchart-customized-effect-1-snap.png
  packages/picasso-charts/src/BarChart/__image_snapshots__/barchart-customized-snap.png
  packages/picasso-charts/src/BarChart/__image_snapshots__/barchart-tooltip-effect-1-snap.png
  packages/picasso-charts/src/BarChart/__image_snapshots__/barchart-tooltip-snap.png
  packages/picasso-charts/src/BarChart/story/index.jsx
  packages/picasso-charts/src/BarChart/test.tsx
Labels: no-jira

#2857 Version Packages [skip ci]
  .changeset/ninety-ligers-scream.md
  .changeset/polite-kiwis-rush.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2868 feat(autocomplete): allow passing popper options
  .changeset/tame-boats-kick.md
  packages/picasso/src/Autocomplete/Autocomplete.tsx
  packages/picasso/src/TagSelector/TagSelector.tsx
Labels: Feature, contribution

#2876 Version Packages [skip ci]
  .changeset/bright-students-crash.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2862 chore: remove redundant parameter from onRemove
  packages/picasso-forms/src/FileInput/FileInput.tsx
Labels: no-jira

#2883 chore: fix picasso-provider version missmatches
  .github/workflows/pr.yaml
  .husky/pre-commit
  packages/picasso/package.json
  packages/shared/package.json
  yarn.lock
Labels: no-jira

#2880 fix(Form): fix field names for form story examples
  packages/picasso-forms/src/Form/story/BackendCommunication.example.tsx
  packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
  packages/picasso-forms/src/Form/story/CustomValidator.example.tsx
  packages/picasso-forms/src/Form/story/Default.example.tsx
  packages/picasso-forms/src/Form/story/Dropzone.example.tsx
  packages/picasso-forms/src/Form/story/FieldRequirements.example.tsx
  packages/picasso-forms/src/Form/story/FileInput.example.tsx
  packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
  packages/picasso-forms/src/Form/story/ParseInput.example.tsx
  packages/picasso-forms/src/Form/story/RichTextEditor.example.tsx
  packages/picasso-forms/src/Form/story/Status.example.tsx
  packages/picasso-forms/src/Form/story/TitleCase.example.tsx
  packages/picasso-forms/src/Form/story/ValidateOnSubmit.example.tsx
Labels: no-jira

#2881 fix: fix type errors and remove redundant prop for storybook components
  .storybook/components/PicassoBook/TabChapter.tsx
  .storybook/components/PicassoBook/components/TabsSection/TabsSection.tsx
  .storybook/utils/documentation-generator.ts
Labels: no-jira

#2831 fix(InputField): fix input valid state when it's changed after submit
  .changeset/happy-dolls-wave.md
  packages/picasso-forms/src/FormConfig/FormConfig.ts
  packages/picasso-forms/src/InputField/InputField.tsx
  packages/picasso-forms/src/InputField/test.ts
Labels: contribution

#2887 Version Packages [skip ci]
  .changeset/gorgeous-donkeys-call.md
  .changeset/happy-dolls-wave.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2889 feat: introduce happo hover screenshot command for cypress
  cypress/component/Checkbox.spec.tsx
  cypress/component/Dropdown.spec.tsx
  cypress/component/TagSelector.spec.tsx
  cypress/support/commands.jsx
  cypress/support/index.d.ts
  yarn.lock
Labels: no-jira

#2838 fix(Form): fix form validation when submit with clicking Enter
  .changeset/nice-guests-act.md
  cypress/component/RichTextEditor.spec.tsx
  packages/picasso-forms/src/Form/Form.tsx
  packages/picasso-forms/src/Form/FormRenderer.tsx
  packages/picasso-forms/src/Form/test.tsx
  packages/picasso/src/RichTextEditor/story/index.jsx
Labels: contribution

#2897 fix: cypress parallelization in CI
  cypress.config.ts
  package.json
  yarn.lock
Labels: no-jira

#2894 chore: use davinci github actions directly
  .changeset/sweet-pugs-fail.md
  .github/dependabot.yml
  .github/workflows/davinci-alpha-package.yml
  .github/workflows/davinci-integration-tests.yml
  .github/workflows/handle-contribution.yml
  .github/workflows/pr.yaml
  .github/workflows/visual-testing.yml
Labels: no-jira

#2908 chore: fix typescript validator
  package.json
  packages/picasso-forms/src/FormConfig/FormConfig.ts
Labels: no-jira

#2899 fix(Modal): refactor Modal's scroll lock to allow multiple modals mounted
  .changeset/slow-oranges-approve.md
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/Modal/test.tsx
  packages/picasso/src/utils/Modal/modal-manager.ts
Labels: contribution

#2900 chore: remove 'Ensure that all PR checks are green' from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-jira

#2918 chore: disable flaky TreeView story screenshots temporarily
  packages/picasso/src/TreeView/story/index.jsx
Labels: no-jira

#2921 Version Packages [skip ci]
  .changeset/fair-chicken-serve.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2920 chore: bump notify jira about contribution version
  .github/workflows/handle-contribution.yml
Labels: no-jira

#2910 chore: use getByTestId and getByRole in Cypress
  cypress/component/ApplicationUpdateNotification.spec.tsx
  cypress/component/BarChart.spec.tsx
  cypress/component/ButtonSplit.spec.tsx
  cypress/component/DatePicker.spec.tsx
  cypress/component/Form.spec.tsx
  cypress/component/Link.spec.tsx
  cypress/component/List.spec.tsx
  cypress/component/Menu.spec.tsx
  cypress/component/PasswordInput.spec.tsx
  cypress/component/RichTextEditor.spec.tsx
  cypress/component/Select.spec.tsx
  cypress/component/ShowMore.spec.tsx
  cypress/component/Table.spec.tsx
  cypress/component/TagSelector.spec.tsx
Labels: no-jira

#2922 Version Packages [skip ci]
  .changeset/short-forks-confess.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2924 chore: fix markdown styles in storybook
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  yarn.lock
Labels: no-jira

#2916 chore(RichTextEditor): add links support to rich text editor
  .changeset/hot-cats-carry.md
  packages/picasso/package.json
  packages/picasso/src/QuillEditor/QuillEditor.tsx
  packages/picasso/src/QuillEditor/constants.ts
  packages/picasso/src/QuillEditor/formats/index.ts
  packages/picasso/src/QuillEditor/formats/link.ts
  packages/picasso/src/QuillEditor/hooks/useQuillInstance/test.tsx
  packages/picasso/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
  packages/picasso/src/QuillEditor/hooks/useSubscribeToTextEditorEvents/useSubscribeToTextEditorEvents.tsx
  packages/picasso/src/QuillEditor/types.ts
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  packages/picasso/src/RichText/story/Default.example.tsx
  packages/picasso/src/RichText/story/HTML.example.tsx
  packages/picasso/src/RichText/types.ts
  packages/picasso/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso/src/RichTextEditor/hooks/useOnSelectionChange/test.ts
  packages/picasso/src/RichTextEditor/hooks/useOnSelectionChange/useOnSelectionChange.tsx
  packages/picasso/src/RichTextEditor/hooks/useOnTextFormat/useOnTextFormat.tsx
  packages/picasso/src/RichTextEditor/hooks/useToolbarHandlers/useToolbarHandlers.tsx
  packages/picasso/src/RichTextEditor/store/toolbar/actionTypes.ts
  packages/picasso/src/RichTextEditor/store/toolbar/actions.ts
  packages/picasso/src/RichTextEditor/store/toolbar/initialState.ts
  packages/picasso/src/RichTextEditor/store/toolbar/reducer.ts
  packages/picasso/src/RichTextEditor/store/toolbar/types.ts
  packages/picasso/src/RichTextEditor/story/Links.example.tsx
  packages/picasso/src/RichTextEditor/story/index.jsx
  packages/picasso/src/RichTextEditor/utils/convertFormat.ts
  packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
  packages/picasso/src/RichTextEditorToolbar/types.ts
  packages/picasso/src/Typography/styles.ts
  packages/picasso/src/utils/html-to-hast.ts
  yarn.lock
Labels: Feature, contribution

#2926 Version Packages [skip ci]
  .changeset/hot-cats-carry.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2929 fix: update contribution workflow
  .github/workflows/handle-contribution.yml
Labels: no-jira

#2928 refactor(Accordion): fix documentation
  packages/picasso/src/Accordion/Accordion.tsx
  packages/picasso/src/Accordion/Details.tsx
  packages/picasso/src/Accordion/Summary.tsx
  packages/picasso/src/Accordion/index.ts
  packages/picasso/src/Accordion/story/index.jsx
  packages/picasso/src/AccordionCompound/index.ts
Labels: no-jira, contribution

#2931 Version Packages [skip ci]
  .changeset/twelve-goats-yawn.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#2930 fix: refactor creating formats
  .changeset/swift-trainers-applaud.md
  packages/picasso/src/QuillEditor/formats/bold.ts
  packages/picasso/src/QuillEditor/formats/header.ts
  packages/picasso/src/QuillEditor/formats/link.ts
Labels: Bugfix, contribution

#2945 Version Packages [skip ci]
  .changeset/swift-trainers-applaud.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2943 fix: improve collapsible section animation
  .changeset/sour-cougars-rhyme.md
  packages/picasso/src/Section/Section.tsx
  packages/picasso/src/Section/__snapshots__/test.tsx.snap
  packages/picasso/src/Section/story/Collapsible.example.tsx
  packages/picasso/src/Section/styles.ts
Labels: contribution

#2952 feat: add inbox icon
  .changeset/angry-countries-wave.md
  packages/picasso/src/Icon/Inbox16.tsx
  packages/picasso/src/Icon/Inbox24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/inbox16.svg
  packages/picasso/src/Icon/svg/inbox24.svg
Labels: contribution

#2954 Version Packages [skip ci]
  .changeset/angry-countries-wave.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
