Repository toptal/picasso, pull requests merged in 2022-09, with the labels that each got.

#3079 feat(AvatarUpload): add visual states
  .changeset/quiet-cameras-carry.md
  packages/picasso/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
  packages/picasso/src/AvatarUpload/story/States.example.tsx
  packages/picasso/src/AvatarUpload/story/index.jsx
  packages/picasso/src/AvatarUpload/styles.ts
Labels: Feature

#3081 Version Packages
  .changeset/quiet-cameras-carry.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3078 chore: lint changesets
  .eslintignore
  package.json
  yarn.lock
Labels: no-jira

#3084 Version Packages
  .changeset/spicy-beans-shop.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3082 feat(AvatarUpload): add field wrapper
  .changeset/cold-parrots-hide.md
  .changeset/giant-shrimps-hope.md
  packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso-forms/src/AvatarUpload/index.ts
  packages/picasso-forms/src/FieldBase/types.ts
  packages/picasso-forms/src/Form/story/AvatarUpload.example.tsx
  packages/picasso-forms/src/Form/story/Default.example.tsx
  packages/picasso-forms/src/Form/story/TitleCase.example.tsx
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/FormCompound/index.ts
  packages/picasso/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso/src/AvatarUpload/types.ts
Labels: Feature

#3085 Version Packages
  .changeset/cold-parrots-hide.md
  .changeset/giant-shrimps-hope.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3083 chore(AvatarUpload): add editing example
  packages/picasso/src/AvatarUpload/story/UsingRef.example.tsx
  packages/picasso/src/AvatarUpload/story/index.jsx
Labels: no-jira

#3087 Version Packages
  .changeset/mighty-radios-sniff.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3088 fix: test for root containers on hast to html
  .changeset/light-cats-argue.md
  packages/picasso/src/utils/__tests__/html-to-hast.test.tsx
  packages/picasso/src/utils/html-to-hast.ts
  packages/picasso/src/utils/test.tsx
Labels: no-jira

#3089 Version Packages
  .changeset/light-cats-argue.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3095 chore(PasswordInput): update error message for invalid password
  .changeset/unlucky-vans-study.md
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
Labels: contribution

#3097 Version Packages
  .changeset/unlucky-vans-study.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3096 feat(Tabs): introduce `orientation` prop
  .changeset/tame-zebras-accept.md
  packages/picasso/src/Tab/Tab.tsx
  packages/picasso/src/Tab/__snapshots__/test.tsx.snap
  packages/picasso/src/Tab/styles.ts
  packages/picasso/src/Tabs/Tabs.tsx
  packages/picasso/src/Tabs/__snapshots__/test.tsx.snap
  packages/picasso/src/Tabs/story/Vertical.example.tsx
  packages/picasso/src/Tabs/story/index.jsx
  packages/picasso/src/Tabs/styles.ts
  packages/picasso/src/Tabs/test.tsx
Labels: contribution

#3102 Version Packages
  .changeset/tame-zebras-accept.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3099 chore: omit PasswordInput adornments
  .changeset/lovely-forks-battle.md
  packages/picasso/src/PasswordInput/PasswordInput.tsx
Labels: Chore, no-jira, contribution

#3105 Version Packages
  .changeset/lovely-forks-battle.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3100 fix(PasswordInput): fix visibility of the password requirements
  .changeset/green-shrimps-dream.md
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
  yarn.lock
Labels: contribution

#3106 Version Packages
  .changeset/green-shrimps-dream.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3104 chore(AvatarUpload): add sourcelink to AvatarUpload
  .changeset/silent-mugs-peel.md
  packages/picasso/src/AvatarUpload/story/index.jsx
Labels: Chore, no-jira, contribution

#3103 fix(Tabs): fix alignment, shadow, and background color for vertical tabs
  .changeset/wet-beans-pump.md
  packages/picasso/src/Tab/styles.ts
  packages/picasso/src/Tabs/story/Vertical.example.tsx
  packages/picasso/src/Tabs/styles.ts
Labels: contribution

#3098 fix(Select): remove internal value state
  .changeset/hip-yaks-move.md
  packages/picasso/src/NonNativeSelect/test.tsx
  packages/picasso/src/SelectBase/hooks/use-select-props/mocks.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/test.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/use-select-handler.ts
  packages/picasso/src/SelectBase/hooks/use-select-state/use-select-state.ts
  packages/picasso/src/SelectBase/types.ts
Labels: Bugfix, no-jira

#3107 Version Packages
  .changeset/hip-yaks-move.md
  .changeset/silent-mugs-peel.md
  .changeset/wet-beans-pump.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3112 fix: use `TypographyOverflow` to show file name inside `Dropzone`
  .changeset/empty-bulldogs-sneeze.md
  packages/picasso/src/Dropzone/story/Multiple.example.tsx
  packages/picasso/src/FileList/__snapshots__/test.tsx.snap
  packages/picasso/src/FileListItem/FileListItem.tsx
  packages/picasso/src/FileListItem/__snapshots__/test.tsx.snap
  packages/picasso/src/FileListItem/styles.ts
Labels: Bugfix, contribution

#3113 Version Packages
  .changeset/empty-bulldogs-sneeze.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3116 chore: automatically merge non-major changeset PRs
  .github/workflows/automerge-release.yaml
Labels: CI

#3117 Changeset release/test automerge tsl
  .changeset/four-hairs-yell.md
  .changeset/mean-pears-nail.md
  .changeset/twelve-bears-rescue.md
  README.md
Labels: no-jira

#3121 chore: update lerna to latest version
  package.json
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
  yarn.lock
Labels: no-jira

#3122 chore: add parameter to remove content text of dropzone
  .changeset/rude-cameras-shake.md
  packages/picasso/src/Dropzone/Dropzone.tsx
  packages/picasso/src/Dropzone/test.tsx
Labels: Chore, no-jira, contribution

#3123 Version Packages
  .changeset/rude-cameras-shake.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3124 chore: lift envars up in the automerge job
  .github/workflows/automerge-release.yaml
Labels: CI
