Repository toptal/picasso, pull requests merged in 2022-08, with the labels that each got.

#3015 fix: broken links in storybook spacing tutorial
  .changeset/few-rules-wink.md
  .storybook/stories/tutorials/spacings/story/index.jsx
Labels: no-jira

#3018 Version Packages
  .changeset/brave-eyes-smell.md
  .changeset/few-rules-wink.md
  .changeset/proud-emus-destroy.md
  .changeset/short-elephants-whisper.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3028 chore: remove unnecessary workflow
  .github/workflows/request-review-on-pr.yml
Labels: no-jira

#3029 feat(Drawer): add transitionProps prop
  .changeset/young-numbers-attack.md
  packages/picasso/src/Drawer/Drawer.tsx
Labels: no-jira, contribution

#3031 Version Packages
  .changeset/young-numbers-attack.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3030 refactor: use modern MUI api
  .changeset/dirty-ties-cover.md
  packages/picasso-provider/src/Picasso/PicassoProvider.tsx
  packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
  packages/picasso/src/Grid/Grid.tsx
  packages/picasso/src/Input/__snapshots__/test.tsx.snap
  packages/picasso/src/Loader/Loader.tsx
  packages/picasso/src/NonNativeSelectLoader/__snapshots__/test.tsx.snap
  packages/picasso/src/OutlinedInput/OutlinedInput.tsx
Labels: no-jira, contribution

#3038 Version Packages
  .changeset/dirty-ties-cover.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3037 fix(calendar): add rule on picasso calendar styles component
  .changeset/shiny-pigs-confess.md
  packages/picasso/src/Calendar/styles.ts
Labels: contribution

#3039 Version Packages
  .changeset/shiny-pigs-confess.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3040 chore: add anvil review in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-jira

#3036 feat(dropdown): add contentStyle prop
  .changeset/khaki-carpets-beam.md
  cypress/component/Dropdown.spec.tsx
  packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
  packages/picasso/src/Dropdown/Dropdown.tsx
  packages/picasso/src/Dropdown/story/CustomStyle.example.tsx
  packages/picasso/src/Dropdown/story/index.jsx
  packages/picasso/src/Dropdown/styles.ts
Labels: Feature, contribution

#3042 Version Packages
  .changeset/khaki-carpets-beam.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3050 chore(cypress): bump to 10.6.0 to run tests in single tab
  package.json
  yarn.lock
Labels: no-jira

#3052 Version Packages
  .changeset/metal-needles-talk.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3051 chore: bump terser to fix vulnerability issue
  yarn.lock
Labels: dependencies

#3057 chore: remove redundant bug fixes doc
  CONTRIBUTING.md
  docs/bug-fixes-in-lts.md
Labels: no-jira

#3062 fix: pass missing props to children when mapping
  .changeset/five-comics-care.md
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  packages/picasso/src/utils/html-to-hast.ts
Labels: Bugfix, no-jira, contribution

#3066 Version Packages
  .changeset/five-comics-care.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3065 feat(Avatar): add editable state
  .changeset/strong-beans-perform.md
  packages/picasso/src/Avatar/Avatar.tsx
  packages/picasso/src/Avatar/story/Editable.example.tsx
  packages/picasso/src/Avatar/story/index.jsx
  packages/picasso/src/Avatar/styles.ts
  packages/picasso/src/Avatar/test.tsx
Labels: Feature

#3067 Version Packages
  .changeset/strong-beans-perform.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3069 feat(AvatarUpload): implement AvatarUpload
  .changeset/blue-eels-compete.md
  cypress/component/AvatarUpload.spec.tsx
  packages/picasso/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
  packages/picasso/src/AvatarUpload/DropzoneSvg/utils.ts
  packages/picasso/src/AvatarUpload/__snapshots__/test.tsx.snap
  packages/picasso/src/AvatarUpload/index.ts
  packages/picasso/src/AvatarUpload/story/Default.example.tsx
  packages/picasso/src/AvatarUpload/story/WithUpload.example.tsx
  packages/picasso/src/AvatarUpload/story/index.jsx
  packages/picasso/src/AvatarUpload/styles.ts
  packages/picasso/src/AvatarUpload/test.tsx
  packages/picasso/src/AvatarUpload/types.ts
  packages/picasso/src/index.ts
Labels: Feature

#3077 feat(AvatarUpload): add size variant
  .changeset/blue-eels-compete.md
  cypress/component/AvatarUpload.spec.tsx
  packages/picasso/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
  packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
  packages/picasso/src/AvatarUpload/DropzoneSvg/utils.ts
  packages/picasso/src/AvatarUpload/__snapshots__/test.tsx.snap
  packages/picasso/src/AvatarUpload/story/Sizes.example.tsx
  packages/picasso/src/AvatarUpload/story/WithUpload.example.tsx
  packages/picasso/src/AvatarUpload/story/index.jsx
  packages/picasso/src/AvatarUpload/styles.ts
Labels: Feature

#3076 Version Packages
  .changeset/blue-eels-compete.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
