Repository toptal/picasso, pull requests merged in 2022-02, with the labels that each got.

#2411 Version Packages [skip ci]
  .changeset/good-zoos-share.md
  .changeset/page-footer-custom-copyright.md
  .changeset/quiet-forks-jam.md
  .changeset/tame-pianos-impress.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2414 fix: add Alex Radulescu as maintainer
  .github/workflows/handle-contribution.yml
Labels: no-jira

#2412 chore: remove picasso-lab reference in README files
  README.md
  packages/picasso-forms/README.md
Labels: no-jira

#2424 Version Packages [skip ci]
  .changeset/silver-nails-hammer.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2428 Version Packages [skip ci]
  .changeset/shaggy-yaks-rule.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2431 Version Packages [skip ci]
  .changeset/odd-queens-play.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2429 fix: remove picasso imports in picasso directory
  packages/picasso/src/AlertInline/AlertInline.tsx
  packages/picasso/src/Breadcrumbs/Breadcrumbs.tsx
  packages/picasso/src/Calendar/Calendar.tsx
  packages/picasso/src/DatePicker/DatePicker.tsx
  packages/picasso/src/Drawer/Drawer.tsx
  packages/picasso/src/Dropzone/Dropzone.tsx
  packages/picasso/src/EmptyStateCollection/EmptyStateCollection.tsx
  packages/picasso/src/HeaderLoader/HeaderLoader.tsx
  packages/picasso/src/MediaSkeletonLoader/MediaSkeletonLoader.tsx
  packages/picasso/src/OverlayBadge/OverlayBadge.tsx
  packages/picasso/src/Popper/Popper.tsx
  packages/picasso/src/Switch/Switch.tsx
  packages/picasso/src/TreeView/PointNode/TreeNodeAvatar.tsx
  packages/picasso/src/TypographyLoader/TypographyLoader.tsx
Labels: no-jira

#2430 test: add proper mock for global `window.matchMedia`
  __tests__/matchMedia.js
  packages/picasso/src/DatePicker/test.tsx
  packages/picasso/src/FileListItem/test.tsx
  packages/picasso/src/Tooltip/__snapshots__/test.tsx.snap
  packages/picasso/src/Tooltip/test.tsx
  packages/picasso/src/TypographyOverflow/test.tsx
Labels: no-jira

#2439 fix: fix dist-package directory not found errors
  bin/build.js
Labels: no-jira

#2443 fix(RichTextEditor): multiple bugs
  packages/picasso/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
  packages/picasso/src/QuillEditor/utils/getFormatChangeHandler/getFormatChangeHandler.ts
  packages/picasso/src/RichTextEditor/hooks/useOnFocus/useOnFocus.tsx
Labels: no-jira

#2446 Version Packages [skip ci]
  .changeset/four-jokes-breathe.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2449 chore: downgrade hast-to-hyperscript since new version is in ESM
  .changeset/rude-dogs-wonder.md
  jest.config.js
  packages/picasso/package.json
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  yarn.lock
Labels: no-jira

#2452 Version Packages [skip ci]
  .changeset/rude-dogs-wonder.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2453 chore: release storybook even if package is not released
  .github/workflows/release.yml
Labels: no-jira

#2457 chore(date-picker): fix an invalid displayed date after clicking in calendar when timezone is set
  .changeset/metal-cherries-drive.md
  packages/picasso/src/DatePicker/DatePicker.tsx
  packages/picasso/src/DatePicker/test.tsx
Labels: Bugfix

#2458 Version Packages [skip ci]
  .changeset/metal-cherries-drive.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2415 chore: refactor picasso lab codemod
  .changeset/kind-dryers-reply.md
  .prettierignore
  packages/picasso-codemod/src/utils/has-top-level-comment.ts
  packages/picasso-codemod/src/utils/index.ts
  packages/picasso-codemod/src/utils/is-import-by-path.ts
  packages/picasso-codemod/src/utils/replace-with.ts
  packages/picasso-codemod/src/v18.0.0/picasso-lab/__testfixtures__/.eslintrc.js
  packages/picasso-codemod/src/v18.0.0/picasso-lab/__testfixtures__/basic.input.tsx
  packages/picasso-codemod/src/v18.0.0/picasso-lab/__testfixtures__/basic.output.tsx
  packages/picasso-codemod/src/v18.0.0/picasso-lab/picasso-lab.ts
  packages/picasso-codemod/src/v18.0.0/picasso-lab/utils.ts
Labels: no-jira

#2465 chore(stepper): change background-color to `inherit`
  .changeset/stale-apples-fix.md
  packages/picasso/src/Stepper/styles.ts
Labels: Bugfix

#2463 Version Packages [skip ci]
  .changeset/kind-dryers-reply.md
  .changeset/stale-apples-fix.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2466 Version Packages [skip ci]
  .changeset/afraid-trees-confess.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2468 Version Packages [skip ci]
  .changeset/cuddly-bulldogs-jam.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2462 feat(PasswordInput): add new component
  .changeset/forty-cooks-flash.md
  .changeset/twenty-clocks-yell.md
  cypress/component/PasswordInput.spec.tsx
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
  packages/picasso-forms/src/PasswordInput/index.ts
  packages/picasso/src/PasswordInput/PasswordInput.tsx
  packages/picasso/src/PasswordInput/index.ts
  packages/picasso/src/PasswordInput/story/Default.example.tsx
  packages/picasso/src/PasswordInput/story/Disabled.example.tsx
  packages/picasso/src/PasswordInput/story/Errored.example.tsx
  packages/picasso/src/PasswordInput/story/index.jsx
  packages/picasso/src/PasswordInput/styles.ts
  packages/picasso/src/PasswordInput/test.tsx
  packages/picasso/src/index.ts
Labels: Feature

#2469 Version Packages [skip ci]
  .changeset/forty-cooks-flash.md
  .changeset/twenty-clocks-yell.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2473 Version Packages [skip ci]
  .changeset/smooth-toys-look.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira
