Repository toptal/picasso, pull requests merged in 2022-07, with the labels that each got.

#2958 chore: add ability to trigger release manually
  .github/workflows/release.yml
Labels: no-jira

#2957 feat: merge Picasso and PicassoLight on storybook
  .storybook/components/PicassoBook/components/TabsSection/TabsSectionHeader.tsx
  packages/picasso-provider/src/Picasso/PicassoLight/story/index.jsx
  packages/picasso-provider/src/Picasso/story/BarePicassoLight.example.tsx
  packages/picasso-provider/src/Picasso/story/LightWithFixViewportAndFontsLoader.example.tsx
  packages/picasso-provider/src/Picasso/story/LightWithNotificationsAndFavicon.example.tsx
  packages/picasso-provider/src/Picasso/story/index.jsx
Labels: no-jira

#2959 chore: bump notistack to 1.0.10
  .changeset/eight-apples-refuse.md
  packages/picasso-provider/package.json
  packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
  packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
  packages/picasso/package.json
  packages/picasso/src/utils/Notifications/__snapshots__/test.tsx.snap
  packages/shared/package.json
  yarn.lock
Labels: no-jira

#2964 docs: add happo screenshot naming rfc
  docs/decisions/08-happo-screenshots-naming.md
Labels: no-jira

#2967 Version Packages [skip ci]
  .changeset/eight-apples-refuse.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#2942 fix(RichTextEditor): use `FieldLabel`
  .changeset/famous-poets-stare.md
  cypress/component/RichTextEditor.spec.tsx
  packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso/src/RichTextEditor/story/Status.example.tsx
  packages/picasso/src/RichTextEditor/styles.ts
Labels: no-jira

#2970 fix(TagSelector): fix options not showing on every click
  .changeset/tame-plums-unite.md
  packages/picasso/src/Autocomplete/Autocomplete.tsx
Labels: contribution

#2971 Version Packages [skip ci]
  .changeset/famous-poets-stare.md
  .changeset/tame-plums-unite.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2953 chore: add a note of how to pass todoless action
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-jira

#2956 docs: add BASE design instructions on PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: no-jira

#2981 feat(modal): adjust modal content top padding
  .changeset/sweet-squids-crash.md
  packages/picasso/src/ModalContent/styles.ts
Labels: no-jira, contribution

#2983 Version Packages [skip ci]
  .changeset/sweet-squids-crash.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2990 feat: update contribution workflow to latest
  .github/workflows/handle-contribution.yml
Labels: no-jira

#2969 feat(TagSelector): add `closeOnSelect` prop
  .changeset/lemon-cups-jump.md
  packages/picasso/src/Autocomplete/Autocomplete.tsx
  packages/picasso/src/Autocomplete/use-autocomplete/test.ts
  packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts
  packages/picasso/src/TagSelector/TagSelector.tsx
  packages/picasso/src/TagSelector/story/KeepOpen.example.tsx
  packages/picasso/src/TagSelector/story/index.jsx
Labels: contribution

#2993 chore: dont add [skip-ci] to Version Package PR
  .github/workflows/release.yml
Labels: no-jira

#2995 docs: add component api principles
  docs/contribution/component-api.md
Labels: no-jira

#2997 feat(stepper): add `overflowEllipsis` prop
  .changeset/light-mugs-prove.md
  cypress/component/Stepper.spec.tsx
  packages/picasso/src/StepLabel/StepLabel.tsx
  packages/picasso/src/StepLabel/styles.ts
  packages/picasso/src/Stepper/Stepper.tsx
  packages/picasso/src/Stepper/story/Overflow.example.tsx
  packages/picasso/src/Stepper/story/index.jsx
  yarn.lock
Labels: Feature, contribution

#2992 Version Packages
  .changeset/light-mugs-prove.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3002 fix(TagSelector): update testids property definition
  .changeset/long-sloths-pump.md
  packages/picasso/src/TagSelector/TagSelector.tsx
Labels: no-jira, contribution

#3003 Version Packages
  .changeset/long-sloths-pump.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3004 chore: bump Davinci to 18.4.2
  package.json
  yarn.lock
Labels: no-jira

#3009 Version Packages
  .changeset/young-grapes-type.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3011 Version Packages
  .changeset/proud-ligers-grab.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2994 feat(DatePicker): add footer and indicated in a range of dates
  .changeset/fluffy-hairs-argue.md
  cypress/component/DatePicker.spec.tsx
  packages/picasso/src/Calendar/Calendar.tsx
  packages/picasso/src/Calendar/styles.ts
  packages/picasso/src/CalendarIndicators/CalendarIndicators.tsx
  packages/picasso/src/CalendarIndicators/index.ts
  packages/picasso/src/CalendarIndicators/styles.ts
  packages/picasso/src/DatePicker/DatePicker.tsx
  packages/picasso/src/DatePicker/story/WithFooter.example.tsx
  packages/picasso/src/DatePicker/story/WithIndicatedRange.example.tsx
  packages/picasso/src/DatePicker/story/index.jsx
  packages/picasso/src/DatePicker/styles.ts
  packages/picasso/src/DatePicker/test.tsx
Labels: contribution

#3017 Version Packages
  .changeset/fluffy-hairs-argue.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3014 fix(TopBarMenu): meta is invisible on small and medium screens
  .changeset/short-elephants-whisper.md
  packages/picasso/src/PageTopBarMenu/PageTopBarMenu.tsx
Labels: contribution

#3019 fix(JenkinsCredentials): replace old Jenkins Triggerbot credentials w…
  .github/workflows/pr.yaml
  .github/workflows/release.yml
Labels: contribution

#3020 ci: add http proxy to env
  .github/workflows/pr.yaml
Labels: no-jira

#3021 fix(DatePicker): fix flaky test
  cypress/component/DatePicker.spec.tsx
  packages/picasso/src/DatePicker/story/WithIndicatedRange.example.tsx
Labels: no-jira
