Repository toptal/picasso, pull requests merged in 2022-03, with the labels that each got.

#2480 Version Packages [skip ci]
  .changeset/breezy-drinks-act.md
  .changeset/cold-students-heal.md
  .changeset/funny-squids-allow.md
  .changeset/seven-drinks-dance.md
  .changeset/swift-toys-reply.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2484 Version Packages [skip ci]
  .changeset/modern-windows-decide.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2486 Version Packages [skip ci]
  .changeset/dirty-points-applaud.md
  .changeset/silent-bananas-mate.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2487 Version Packages [skip ci]
  .changeset/angry-eels-doubt.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2495 Version Packages [skip ci]
  .changeset/yellow-snakes-yell.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#2499 feat(RichText): enable value in html string format
  .changeset/slimy-goats-breathe.md
  .prettierignore
  @types/hast-util-from-dom/index.d.ts
  packages/picasso/package.json
  packages/picasso/src/RichText/RichText.tsx
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  packages/picasso/src/RichText/story/HTML.example.tsx
  packages/picasso/src/RichText/story/index.jsx
  packages/picasso/src/RichText/types.ts
  packages/picasso/src/utils/html-to-hast.ts
  packages/picasso/src/utils/index.ts
  packages/picasso/src/utils/test.tsx
  yarn.lock
Labels: no-jira

#2481 feat(RatingStars): rename old Rating component to Rating.Stars
  .changeset/cyan-games-relax.md
  .changeset/dull-dragons-battle.md
  .changeset/grumpy-crabs-exist.md
  cypress/component/Rating.spec.tsx
  cypress/component/RatingThumbs.spec.tsx
  package.json
  packages/picasso-codemod/README.md
  packages/picasso-codemod/bin/cli.mjs
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/__testfixtures__/basic.input.tsx
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/__testfixtures__/basic.output.tsx
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/__testfixtures__/forms.input.tsx
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/__testfixtures__/forms.output.tsx
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/__tests__/test.ts
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/index.js
  packages/picasso-codemod/src/v19.0.0/rename-rating-stars/rename-rating-stars.js
  packages/picasso-forms/src/Form/story/Default.example.tsx
  packages/picasso-forms/src/Form/story/TitleCase.example.tsx
  packages/picasso-forms/src/Rating/Rating.tsx
  packages/picasso-forms/src/Rating/test.tsx
  packages/picasso/src/Rating/index.ts
  packages/picasso/src/RatingIcon/RatingIcon.tsx
  packages/picasso/src/RatingStars/RatingStars.tsx
  packages/picasso/src/RatingStars/__image_snapshots__/rating-custom-icon-snap.png
  packages/picasso/src/RatingStars/__image_snapshots__/rating-default-snap.png
  packages/picasso/src/RatingStars/__image_snapshots__/rating-non-interactive-snap.png
  packages/picasso/src/RatingStars/__image_snapshots__/rating-readonly-snap.png
  packages/picasso/src/RatingStars/__snapshots__/test.tsx.snap
  packages/picasso/src/RatingStars/index.ts
  packages/picasso/src/RatingStars/story/CustomIcons.example.tsx
  packages/picasso/src/RatingStars/story/Default.example.tsx
  packages/picasso/src/RatingStars/story/NonInteractive.example.tsx
  packages/picasso/src/RatingStars/story/Sizes.example.tsx
  packages/picasso/src/RatingStars/story/index.jsx
  packages/picasso/src/RatingStars/styles.ts
  packages/picasso/src/RatingStars/test.tsx
  packages/picasso/src/index.ts
Labels: BREAKING CHANGE

#2504 Version Packages [skip ci]
  .changeset/cyan-games-relax.md
  .changeset/dull-dragons-battle.md
  .changeset/grumpy-crabs-exist.md
  .changeset/slimy-goats-breathe.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2529 chore: move reset button functionality to input field
  packages/picasso-forms/package.json
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/InputFieldWrapper/InputFieldWrapper.tsx
  packages/picasso-forms/src/utils/use-form-input-reset/index.ts
  packages/picasso-forms/src/utils/use-form-input-reset/test.ts
  packages/picasso-forms/src/utils/use-form-input-reset/use-form-input-reset.ts
Labels: no-jira

#2531 Version Packages [skip ci]
  .changeset/breezy-jobs-boil.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2328 chore: test changeset experimental flag
  .changeset/config.json
Labels: no-jira

#2530 chore: extract label from field wrapper
  packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
  packages/picasso-forms/src/ButtonCheckbox/ButtonCheckbox.tsx
  packages/picasso-forms/src/Checkbox/Checkbox.tsx
  packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso-forms/src/DatePicker/DatePicker.tsx
  packages/picasso-forms/src/Dropzone/Dropzone.tsx
  packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
  packages/picasso-forms/src/FieldLabel/__snapshots__/test.tsx.snap
  packages/picasso-forms/src/FieldLabel/index.ts
  packages/picasso-forms/src/FieldLabel/test.tsx
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/FileInput/FileInput.tsx
  packages/picasso-forms/src/Input/Input.tsx
  packages/picasso-forms/src/NumberInput/NumberInput.tsx
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
  packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
  packages/picasso-forms/src/Rating/Rating.tsx
  packages/picasso-forms/src/Select/Select.tsx
  packages/picasso-forms/src/Switch/Switch.tsx
  packages/picasso-forms/src/TagSelector/TagSelector.tsx
  packages/picasso-forms/src/TimePicker/TimePicker.tsx
  packages/picasso/src/PageHead/PageHead.tsx
  packages/picasso/src/test-utils/TestingPicasso.tsx
  packages/shared/src/types.ts
Labels: no-jira

#2538 fix: add prettier resolution
  package.json
  yarn.lock
Labels: no-jira

#2540 Version Packages [skip ci]
  .changeset/neat-nails-live.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#2541 fix: rating label in Form
  packages/picasso-forms/src/Form/index.ts
  packages/picasso-forms/src/Rating/Rating.tsx
  packages/picasso-forms/src/Rating/__snapshots__/test.tsx.snap
  packages/picasso-forms/src/Rating/test.tsx
  packages/picasso/src/DatePicker/DatePicker.tsx
Labels: no-jira

#2543 fix(OverlayBadge): [SPC-1728] fix number alignment on small variant
  .changeset/little-squids-jog.md
  packages/picasso/src/OverlayBadge/__image_snapshots__/overlaybadge-sizes-snap.png
  packages/picasso/src/OverlayBadge/styles.ts
Labels: Bugfix

#2545 Version Packages [skip ci]
  .changeset/little-squids-jog.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2548 refactor: extract error validation from field wrapper
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/Form/FormContext.ts
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/utils/index.ts
  packages/picasso-forms/src/utils/use-field-validation/index.ts
  packages/picasso-forms/src/utils/use-field-validation/test.tsx
  packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
Labels: no-jira

#2550 chore: rename FieldWrapper to Field
  packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
  packages/picasso-forms/src/ButtonCheckbox/ButtonCheckbox.tsx
  packages/picasso-forms/src/Checkbox/Checkbox.tsx
  packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso-forms/src/DatePicker/DatePicker.tsx
  packages/picasso-forms/src/Dropzone/Dropzone.tsx
  packages/picasso-forms/src/Field/Field.tsx
  packages/picasso-forms/src/Field/index.ts
  packages/picasso-forms/src/Field/story/index.jsx
  packages/picasso-forms/src/FieldWrapper/index.ts
  packages/picasso-forms/src/FileInput/FileInput.tsx
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/Input/Input.tsx
  packages/picasso-forms/src/InputField/InputField.tsx
  packages/picasso-forms/src/InputField/index.ts
  packages/picasso-forms/src/InputField/test.ts
  packages/picasso-forms/src/InputFieldWrapper/index.ts
  packages/picasso-forms/src/NumberInput/NumberInput.tsx
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
  packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
  packages/picasso-forms/src/Rating/Rating.tsx
  packages/picasso-forms/src/Select/Select.tsx
  packages/picasso-forms/src/Switch/Switch.tsx
  packages/picasso-forms/src/TagSelector/TagSelector.tsx
  packages/picasso-forms/src/TimePicker/TimePicker.tsx
  packages/picasso-forms/src/index.ts
  packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts
Labels: no-jira

#2551 chore: remove focus after scroll to invalid
  packages/picasso-forms/src/utils/scroll-to.ts
Labels: Chore

#2556 ci: add sshagent to picasso-master-publish-docs job
  ci/jobs/picasso-master-publish-docs/Jenkinsfile
Labels: no-jira

#2553 fix: return back old field wrapper
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/FieldWrapper/index.ts
  packages/picasso-forms/src/FieldWrapper/story/index.jsx
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/index.ts
Labels: no-jira

#2560 Version Packages [skip ci]
  .changeset/forty-paws-deliver.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2562 Version Packages [skip ci]
  .changeset/clean-comics-sparkle.md
  .changeset/hungry-tomatoes-impress.md
  .changeset/six-crews-cover.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2574 fix: type export for field props
  packages/picasso-forms/src/FieldWrapper/index.ts
Labels: no-jira

#2567 Version Packages [skip ci]
  .changeset/three-coins-yell.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
