Repository toptal/picasso, pull requests merged in 2022-11, with the labels that each got.

#3193 feat(AutoSave): create form-values-change decorator
  .changeset/violet-jokes-deny.md
  packages/picasso-forms/src/Form/story/AutoSave.example.tsx
  packages/picasso-forms/src/Form/story/index.jsx
  packages/picasso-forms/src/index.ts
  packages/picasso-forms/src/utils/form-values-change-decorator/form-values-change-decorator.ts
  packages/picasso-forms/src/utils/form-values-change-decorator/index.ts
  packages/picasso-forms/src/utils/form-values-change-decorator/test.tsx
  packages/picasso-forms/src/utils/index.ts
Labels: Feature

#3199 Version Packages
  .changeset/violet-jokes-deny.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3203 Version Packages
  .changeset/wise-yaks-care.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3206 feat: add row-reverse and column-reverse values to direction property…
  .changeset/wise-forks-move.md
  packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
  packages/picasso/src/Container/Container.tsx
  packages/picasso/src/Container/styles.ts
Labels: contribution

#3208 Version Packages
  .changeset/wise-forks-move.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3214 chore(deps): bump loader-utils to fix critical vulnerability
  yarn.lock
Labels: no-jira

#3215 chore(deps): bump and remove recursive-readdir from resolutions
  package.json
  yarn.lock
Labels: dependencies, no-jira

#3216 chore: create dependency review action
  .github/workflows/pr.yaml
Labels: no-jira

#3232 chore: remove run from happo command
  package.json
Labels: no-jira

#3227 chore: run danger check when PR title changes
  .github/workflows/danger.yaml
  .github/workflows/pr.yaml
Labels: no-jira

#3234 Version Packages
  .changeset/seven-cooks-judge.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3239 Version Packages
  .changeset/rotten-shrimps-do.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3240 chore(deps): bump loader-utils to fix vulnerabilities
  yarn.lock
Labels: dependencies

#3235 feat(NotificationsProvider): provide maxNotifications props
  .changeset/warm-berries-sleep.md
  packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
  packages/picasso-provider/src/Picasso/NotificationsProvider/index.ts
  packages/picasso-provider/src/Picasso/NotificationsProvider/test.tsx
  packages/picasso-provider/src/Picasso/index.ts
  packages/picasso-provider/src/index.ts
  packages/picasso/src/utils/Notifications/story/CustomPosition.example.tsx
  packages/picasso/src/utils/Notifications/story/MaxNotifications.example.tsx
  packages/picasso/src/utils/Notifications/story/index.jsx
Labels: contribution

#3247 Version Packages
  .changeset/late-dancers-approve.md
  .changeset/many-badgers-burn.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#3249 Version Packages
  .changeset/good-carpets-change.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
