Repository toptal/picasso, pull requests merged in 2022-04, with the labels that each got.

#2566 fix: handle empty children of ReactNode
  .changeset/late-vans-type.md
  packages/picasso/src/RichText/hooks/useRichText/test.tsx
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  packages/picasso/src/RichText/story/HTML.example.tsx
  packages/picasso/src/RichText/story/index.jsx
  packages/picasso/src/RichTextEditor/hooks/useOnFocus/useOnFocus.tsx
Labels: no-jira

#2580 Version Packages [skip ci]
  .changeset/soft-radios-deny.md
  .changeset/two-turkeys-invite.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2582 Version Packages [skip ci]
  .changeset/late-vans-type.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2581 chore: try to fix flake test by focusing editor before writing
  cypress/component/RichTextEditor.spec.tsx
Labels: no-jira

#2584 ci: fix sshagent in docs Jenkinsfile
  ci/jobs/picasso-master-publish-docs/Jenkinsfile
Labels: no-jira

#2575 feat(BarChart): add hideBarLabel prop which hides label of each bar
  .changeset/seven-terms-sniff.md
  cypress/component/BarChart.spec.tsx
  packages/picasso-charts/src/BarChart/BarChart.tsx
  packages/picasso-charts/src/BarChart/story/HideBarLabel.example.tsx
  packages/picasso-charts/src/BarChart/story/index.jsx
  packages/picasso-charts/src/BarChart/test.tsx
Labels: Feature

#2587 Version Packages [skip ci]
  .changeset/seven-terms-sniff.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#2593 Version Packages [skip ci]
  .changeset/few-seals-talk.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#2585 ci: fix sshagent in temploy kill job
  ci/jobs/picasso-kill-temploys/Jenkinsfile
Labels: no-jira

#2569 chore: upgrade typescript version
  .changeset/tidy-penguins-rush.md
  package.json
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
  yarn.lock
Labels: DO NOT MERGE

#2594 Version Packages [skip ci]
  .changeset/tidy-penguins-rush.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2597 chore: move storybook addon to dev dependencies
  .changeset/strong-penguins-accept.md
  packages/picasso/package.json
Labels: no-jira

#2596 Version Packages [skip ci]
  .changeset/popular-beans-turn.md
  .changeset/strong-penguins-accept.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2589 fix(DatePicker): fix DatePicker disabled state
  .changeset/sour-monkeys-design.md
  packages/picasso/src/DatePicker/DatePicker.tsx
Labels: no-jira

#2600 chore: fix dependabot by removing secrets
  .github/dependabot.yml
Labels: no-jira

#2608 chore: replace manual docs with auto for AnalyticsChart
  .storybook/main.js
  .storybook/utils/documentation-generator.ts
  packages/topkit-analytics-charts/src/AnalyticsChart/AnalyticsChart.tsx
  packages/topkit-analytics-charts/src/AnalyticsChart/story/index.jsx
Labels: no-jira

#2609 chore: relative path for Jacqueline
  cypress/component/Avatar.spec.tsx
  packages/picasso/src/StaticTreeView/story/Default.example.tsx
  packages/picasso/src/StaticTreeView/story/Horizontal.example.tsx
  packages/picasso/src/TreeView/story/CustomZoom.example.tsx
  packages/picasso/src/TreeView/story/Default.example.tsx
  packages/picasso/src/TreeView/story/Horizontal.example.tsx
  packages/picasso/src/TreeView/story/Modal.example.tsx
Labels: no-jira

#2613 chore: move docs publishing to GHA
  .github/workflows/pr.yaml
  ci/jobs/picasso-pr-specs/Jenkinsfile
Labels: no-jira

#2622 Version Packages [skip ci]
  .changeset/selfish-turtles-remember.md
  .changeset/yellow-rivers-agree.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2624 chore: update storybook
  .storybook/main.js
  package.json
  yarn.lock
Labels: dependencies, no-jira

#2625 chore: update async to remove vulnerability
  package.json
  yarn.lock
Labels: no-jira

#2631 fix: skip ci commit message for changesets
  .github/workflows/release.yml
Labels: no-jira

#2629 fix: remove handle contributions from Version Package check
  .github/workflows/handle-contribution.yml
Labels: no-jira

#2628 Version Packages [skip ci]
  .changeset/two-ducks-fry.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: DO NOT MERGE, no-jira

#2637 Version Packages [skip ci]
  .changeset/dry-eyes-pump.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2638 chore: update styled-components
  packages/picasso/package.json
  yarn.lock
Labels: dependencies, no-jira

#2627 chore: update cypress and happo
  .github/workflows/pr.yaml
  .github/workflows/visual-testing.yml
  README.md
  cypress/plugins/index.js
  package.json
  yarn.lock
Labels: dependencies, no-jira

#2641 Version Packages [skip ci]
  .changeset/rare-chefs-remain.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#2646 chore: add alpha package workflow
  .github/workflows/davinci-alpha-package.yml
Labels: no-jira

#2647 chore: update NPM_TOKEN
  .github/workflows/davinci-alpha-package.yml
Labels: no-jira

#2643 chore(tooltip): add `followCursor` prop based on implementation from `@material-ui@5+`
  .changeset/wild-vans-enjoy.md
  packages/picasso/src/Tooltip/Tooltip.tsx
  packages/picasso/src/Tooltip/story/FollowCursor.example.tsx
  packages/picasso/src/Tooltip/story/index.jsx
  packages/picasso/src/Tooltip/test.tsx
  packages/picasso/src/Tooltip/types.ts
  packages/picasso/src/Tooltip/useTooltipFollowCursor.ts
  packages/picasso/src/Tooltip/useTooltipHandlers.ts
  packages/picasso/src/Tooltip/useTooltipState.ts
Labels: Feature

#2653 Version Packages [skip ci]
  .changeset/wild-vans-enjoy.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2644 chore: update babel
  package.json
  yarn.lock
Labels: dependencies, no-jira

#2620 chore: upgrade davinci to 12 version
  jest.config.js
  package.json
  packages/picasso-charts/src/BarChart/utils/find-top-domain/test.ts
  packages/picasso-charts/src/LineChart/utils/find-top-domain/test.ts
  packages/picasso-codemod/src/v18.0.0/picasso-lab/utils.ts
  packages/picasso-forms/src/Form/Form.tsx
  packages/picasso-forms/src/story/Deserialization.example.tsx
  packages/picasso-provider/src/Picasso/config/test.ts
  packages/picasso/src/Autocomplete/test.tsx
  packages/picasso/src/DatePicker/test.tsx
  packages/picasso/src/FileListItem/test.tsx
  packages/picasso/src/NonNativeSelect/test.tsx
  packages/picasso/src/NonNativeSelectOption/test.tsx
  packages/picasso/src/PromptModal/test.tsx
  packages/picasso/src/RatingThumbs/test.tsx
  packages/picasso/src/RichText/hooks/useRichText/test.tsx
  packages/picasso/src/Select/hooks/use-select-state/test.ts
  packages/picasso/src/Select/utils/count-options/test.ts
  packages/picasso/src/Select/utils/get-multiple-selection/test.ts
  packages/picasso/src/Select/utils/get-next-wrapping-index/test.ts
  packages/picasso/src/Select/utils/get-single-selection/test.ts
  packages/picasso/src/Select/utils/normalize-arrow-key/test.ts
  packages/picasso/src/TagSelector/test.tsx
  packages/picasso/src/Typography/utils/to-mui-variant/test.ts
  packages/picasso/src/TypographyOverflow/test.tsx
  yarn.lock
Labels: no-jira

#2657 Version Packages [skip ci]
  .changeset/bright-phones-think.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2652 fix(FieldWrapper): switch from Field to InputField to pass status
  .changeset/smooth-jeans-turn.md
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/FieldWrapper/test.tsx
Labels: Bugfix

#2658 Version Packages [skip ci]
  .changeset/smooth-jeans-turn.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2662 chore(modal content): clear `update shades` debounce on component unmount
  .changeset/chilled-adults-poke.md
  packages/picasso/src/ModalContent/hooks/test.tsx
  packages/picasso/src/ModalContent/hooks/use-scrollable-shades.ts
Labels: no-jira

#2663 Version Packages [skip ci]
  .changeset/chilled-adults-poke.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2670 Version Packages [skip ci]
  .changeset/sixty-doors-type.md
  .changeset/smooth-laws-explain.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2673 chore: upgrade husky
  .husky/pre-commit
  package.json
  yarn.lock
Labels: no-jira

#2661 chore(deps): bump d3 packages
  packages/picasso-charts/package.json
  packages/picasso/package.json
  packages/picasso/src/TreeView/TreeViewContainer.tsx
  packages/picasso/src/TreeView/useTree.ts
  packages/picasso/src/TreeView/useZoom.ts
  packages/topkit-analytics-charts/package.json
  yarn.lock
Labels: dependencies, no-jira

#2675 fix(Notification): do not show left ellipses if not needed
  .changeset/large-cobras-jam.md
  packages/picasso/src/Pagination/utils/has-ellipsises/has-ellipsises.ts
  packages/picasso/src/Pagination/utils/has-ellipsises/test.ts
Labels: no-jira

#2677 Version Packages [skip ci]
  .changeset/large-cobras-jam.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2660 chore: clean up old TODOs
  jest-setup-dom.js
  packages/picasso/src/NativeSelect/NativeSelect.tsx
  packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
  packages/picasso/src/index.ts
  puppeteer/index.ts
Labels: no-jira

#2676 chore: use davinci for code generating
  _templates/example/new/example.ejs.t
  _templates/example/new/index.js
  _templates/example/new/story.ejs.t
  package.json
  yarn.lock
Labels: no-jira

#2693 fix(ImageAvatar): prevent image blur on downscaled image
  .changeset/prevent-avatar-image-blur.md
  packages/picasso/src/Avatar/ImageAvatar/styles.ts
Labels: contribution

#2706 Version Packages [skip ci]
  .changeset/prevent-avatar-image-blur.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2703 chore: update the base README
  .storybook/manager-head.html
  .storybook/public/production-32x32.png
  .storybook/stories/picasso/story/index.tsx
  README.md
  docs/contribution/github-workflow.md
  packages/picasso/README.md
Labels: contribution
