Repository toptal/picasso, pull requests merged in 2022-05, with the labels that each got.

#2698 fix: make autofill work for controlled input in Firefox
  .changeset/olive-keys-protect.md
  packages/picasso-forms/package.json
  packages/picasso-forms/src/Field/Field.tsx
Labels: Bugfix, contribution

#2711 Version Packages [skip ci]
  .changeset/olive-keys-protect.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2717 Version Packages [skip ci]
  .changeset/dry-plums-accept.md
  .changeset/khaki-moons-change.md
  .changeset/perfect-zebras-trade.md
  .changeset/red-socks-fly.md
  .changeset/selfish-nails-lick.md
  .changeset/thin-toys-kick.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2716 fix: storybook links
  .storybook/components/PicassoBook/Chapter.tsx
  src/utils/url-generator.ts
Labels: no-jira

#2723 fix(Select): pass proper `name` to `FieldLabel`
  .changeset/warm-ducks-move.md
  cypress/component/Calendar.spec.tsx
  packages/picasso-forms/src/Select/Select.tsx
Labels: Bugfix, contribution

#2725 Version Packages [skip ci]
  .changeset/warm-ducks-move.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#2718 chore: document decision about changeset verb tense
  docs/decisions/template.md
  packages/picasso/README.md
Labels: no-jira

#2735 fix: raise error from rsync if error
  ci/jobs/picasso-master-publish-docs/Jenkinsfile
Labels: no-jira

#2742 docs(decision): jest snapshot update as breaking changes
  docs/decisions/01-jest-snapshots-breaking-change.md
Labels: no-jira

#2736 chore: generate props automatically for Button
  packages/picasso/src/Button/Button.tsx
  packages/picasso/src/Button/story/index.jsx
Labels: no-jira

#2731 docs: add changeset verb tense decisions
  docs/contribution/changeset-guidelines.md
  docs/decisions/changeset-verb-tense.md
Labels: no-jira

#2746 Version Packages [skip ci]
  .changeset/happy-pens-talk.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2748 feat: slack message on failed deploy with link to jenkins job
  .github/workflows/release.yml
Labels: no-jira

#2750 chore: sync @types/react-helmet with react-helmet
  packages/picasso/package.json
  yarn.lock
Labels: no-jira, contribution

#2749 Version Packages [skip ci]
  .changeset/curvy-toys-march.md
  .changeset/cyan-tomatoes-think.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2728 chore: add proposal for MUIv5 migration
  docs/decisions/mui-v5-migration.md
Labels: no-jira

#2755 docs: update naming
  docs/decisions/00-template.md
  docs/decisions/02-changeset-verb-tense.md
  docs/decisions/03-mui-v5-migration.md
Labels: no-jira

#2744 fix: fix console warnings and errors for dev environment
  .prettierignore
  .storybook/addons/menu-expand/index.js
  .storybook/addons/menu-expand/register.js
  .storybook/main.js
  packages/picasso-charts/src/BarChart/story/Customized.example.tsx
  packages/picasso-charts/src/BarChart/story/Default.example.tsx
  packages/picasso-charts/src/BarChart/story/HideBarLabel.example.tsx
  packages/picasso-charts/src/BarChart/story/Tooltip.example.tsx
  packages/picasso-forms/src/Form/story/BackendCommunication.example.tsx
  packages/picasso-forms/src/Form/story/CustomValidator.example.tsx
  packages/picasso-forms/src/Form/story/Default.example.tsx
  packages/picasso-forms/src/Form/story/Dropzone.example.tsx
  packages/picasso-forms/src/Form/story/FieldRequirements.example.tsx
  packages/picasso-forms/src/Form/story/FileInput.example.tsx
  packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
  packages/picasso-forms/src/Form/story/RichTextEditor.example.tsx
  packages/picasso-forms/src/Form/story/TitleCase.example.tsx
  packages/picasso-forms/src/Form/story/ValidateOnSubmit.example.tsx
  packages/picasso/src/ButtonGroup/story/ButtonGroupNested.example.tsx
  packages/picasso/src/FieldRequirements/story/Error.example.tsx
  packages/picasso/src/OverviewBlock/OverviewBlock.tsx
  packages/picasso/src/OverviewBlock/story/index.jsx
  packages/picasso/src/PageHead/__image_snapshots__/pagehead-steps-snap.png
  packages/picasso/src/PageHead/story/Steps.example.tsx
  packages/picasso/src/PageSidebar/index.ts
  packages/picasso/src/SidebarItem/index.ts
  packages/picasso/src/Typography/story/Decoration.example.tsx
  packages/picasso/src/utils/Breakpoints/story/useScreens.example.tsx
  packages/topkit-analytics-charts/src/CategoriesChart/story/Default.example.tsx
Labels: no-jira

#2759 Version Packages [skip ci]
  .changeset/tender-lions-dance.md
  .changeset/tiny-candles-vanish.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2761 fix: import correct sidebar in layout tutorial
  .storybook/stories/tutorials/layout/story/Layout.3.example.tsx
  .storybook/stories/tutorials/layout/story/Layout.4.example.tsx
  .storybook/stories/tutorials/layout/story/Layout.final.example.tsx
Labels: no-jira

#2763 chore: bump provider version in shared
  packages/shared/package.json
Labels: no-jira

#2765 fix: zero content case for Badge
  .changeset/shiny-spiders-complain.md
  packages/picasso/src/Badge/Badge.tsx
  packages/picasso/src/Badge/test.tsx
Labels: contribution

#2771 Version Packages [skip ci]
  .changeset/shiny-spiders-complain.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2760 chore: extract internal adornment components from Input
  packages/picasso/src/Input/Input.tsx
  packages/picasso/src/Input/__snapshots__/test.tsx.snap
  packages/picasso/src/Input/styles.ts
  packages/picasso/src/InputIconAdornment/InputIconAdornment.tsx
  packages/picasso/src/InputIconAdornment/index.ts
  packages/picasso/src/InputIconAdornment/styles.ts
  packages/picasso/src/InputLimitAdornment/InputLimitAdornment.tsx
  packages/picasso/src/InputLimitAdornment/index.ts
  packages/picasso/src/InputLimitAdornment/styles.ts
  packages/picasso/src/TimePicker/__snapshots__/test.tsx.snap
Labels: no-jira

#2757 chore: remove .yarn files from repo
  .gitattributes
Labels: no-jira

#2758 style(Input): show success icon at the bottom of multiline input
  .changeset/large-socks-give.md
  packages/picasso/src/Input/Input.tsx
  packages/picasso/src/Input/__snapshots__/test.tsx.snap
  packages/picasso/src/Input/story/Status.example.tsx
  packages/picasso/src/InputLimitAdornment/styles.ts
  packages/picasso/src/InputMultilineAdornment/InputMultilineAdornment.tsx
  packages/picasso/src/InputMultilineAdornment/index.ts
  packages/picasso/src/InputMultilineAdornment/styles.ts
  packages/picasso/src/InputValidIconAdornment/InputValidIconAdornment.tsx
  packages/picasso/src/InputValidIconAdornment/index.ts
  packages/picasso/src/OutlinedInput/OutlinedInput.tsx
Labels: contribution

#2794 Version Packages [skip ci]
  .changeset/shiny-lemons-teach.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2762 fix(codemod): fix removing children's attribute
  packages/picasso-codemod/README.md
  packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/__testfixtures__/children-with-variant.input.tsx
  packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/__testfixtures__/children-with-variant.output.tsx
  packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/__tests__/test.ts
  packages/picasso-codemod/src/v20.0.0/remove-tooltip-variant/remove-tooltip-variant.ts
Labels: no-jira

#2803 Version Packages [skip ci]
  .changeset/breezy-cheetahs-guess.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2806 fix(dep): update semver range for react
  .changeset/happy-parents-reply.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/package.json
  packages/picasso-forms/package.json
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2801 feat: add new `buttonLabel` prop to `FileInput`
  .changeset/fair-hotels-attack.md
  cypress/component/FileInput.spec.tsx
  packages/picasso/src/FileInput/FileInput.tsx
  packages/picasso/src/FileInput/__snapshots__/test.tsx.snap
  packages/picasso/src/FileInput/story/CustomButtonLabel.example.tsx
  packages/picasso/src/FileInput/story/index.jsx
  packages/picasso/src/FileInput/test.tsx
Labels: contribution

#2809 feat: added cube icon
  .changeset/large-ways-arrive.md
  packages/picasso/src/Icon/Box16.tsx
  packages/picasso/src/Icon/Box24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/box16.svg
  packages/picasso/src/Icon/svg/box24.svg
Labels: contribution

#2811 Version Packages [skip ci]
  .changeset/fair-hotels-attack.md
  .changeset/happy-parents-reply.md
  .changeset/large-ways-arrive.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#2812 chore: improve the look of PoweredByGoogle label of the Autocomplete
  .changeset/famous-dragons-kick.md
  packages/picasso/src/Autocomplete/Autocomplete.tsx
  packages/picasso/src/Autocomplete/PoweredByGoogle.tsx
  packages/picasso/src/Autocomplete/styles.ts
Labels: contribution

#2819 Version Packages [skip ci]
  .changeset/famous-dragons-kick.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#2816 fix: visual-testing wf after PR merge
  .github/workflows/visual-testing.yml
Labels: no-jira

#2834 chore(happo): add happo tests to visual-testing.yml
  .github/workflows/release.yml
  .github/workflows/visual-testing.yml
Labels: no-jira
