Repository toptal/picasso, pull requests merged in 2023-06, with the labels that each got.

#3591 feat(BarChart): add option to format the value axis
  .changeset/cyan-plums-cheat.md
  packages/picasso-charts/src/BarChart/BarChart.tsx
  packages/picasso-charts/src/BarChart/story/ValueAxisTickFormatter.example.tsx
  packages/picasso-charts/src/BarChart/story/index.jsx
Labels: contribution

#3592 Version Packages
  .changeset/cyan-plums-cheat.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3599 test: remove flaky snapshot
  packages/picasso/src/Tooltip/__snapshots__/test.tsx.snap
  packages/picasso/src/Tooltip/test.tsx
Labels: no-jira

#3594 feat: add solid pause icon
  .changeset/small-shrimps-hammer.md
  packages/picasso/src/Icon/PauseSolid16.tsx
  packages/picasso/src/Icon/PauseSolid24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/pauseSolid16.svg
  packages/picasso/src/Icon/svg/pauseSolid24.svg
Labels: contribution

#3600 Version Packages
  .changeset/small-shrimps-hammer.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3603 chore: update davinci-github-actions
  .github/workflows/danger.yaml
  .github/workflows/davinci-alpha-package.yml
  .github/workflows/davinci-integration-tests.yml
  .github/workflows/handle-contribution.yml
  .github/workflows/pr.yaml
  .github/workflows/release.yml
  .github/workflows/visual-testing.yml
Labels: no-jira

#3605 Version Packages
  .changeset/tall-bottles-camp.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3611 Version Packages
  .changeset/stupid-bears-turn.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3616 fix: show useBreakpoint code example in storybook
  .changeset/chilly-actors-thank.md
  packages/picasso/src/utils/Breakpoints/story/index.jsx
Labels: no-jira, contribution

#3617 Version Packages
  .changeset/chilly-actors-thank.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3612 fix: remove unused showTwoMonths
  .changeset/cyan-seas-enjoy.md
  packages/picasso/src/DatePicker/DatePicker.tsx
Labels: no-jira

#3619 Version Packages
  .changeset/cyan-seas-enjoy.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3610 fix(ModalContent): [TOP-3334] proper bottom edge detection for scrolling shades
  .changeset/curly-rice-cough.md
  packages/picasso/src/ModalContent/hooks/use-scrollable-shades.ts
Labels: contribution

#3629 Version Packages
  .changeset/afraid-elephants-bake.md
  .changeset/famous-pears-crash.md
  .changeset/stupid-onions-peel.md
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3627 fix: remove unused imports
  .storybook/components/PicassoBook/components/TabsSection/TabsSection.tsx
Labels: no-jira

#3633 Version Packages
  .changeset/perfect-chairs-fold.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3639 feat(ButtonGroup): [SDE-1090] Add disabled appearance
  .changeset/lazy-poets-change.md
  packages/picasso/src/Button/styles.ts
  packages/picasso/src/ButtonGroup/story/ButtonGroupDisabled.example.tsx
  packages/picasso/src/ButtonGroup/story/index.jsx
  packages/picasso/src/ButtonGroupItem/ButtonGroupItem.tsx
  packages/picasso/src/ButtonGroupItem/styles.ts
  packages/picasso/src/PaginationButton/styles.ts
Labels: contribution

#3642 Version Packages
  .changeset/lazy-poets-change.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3648 Version Packages
  .changeset/clever-readers-exist.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
Labels: no-jira

#3649 Version Packages
  .changeset/long-rice-sneeze.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3640 docs: add RFC for custom label in overview block
  docs/decisions/16-custom-label-for-overview-block.md
Labels: docs, contribution

#3654 fix: flaky test
  cypress/component/TypographyOverflow.spec.tsx
Labels: no-jira

#3667 Version Packages
  .changeset/soft-steaks-cheer.md
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3664 fix: version in RichTextEditor codemod
  .changeset/khaki-experts-tan.md
  packages/picasso-codemod/src/v36.0.0/rich-text-editor-replacement.ts
Labels: no-jira

#3669 Version Packages
  .changeset/khaki-experts-tan.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
Labels: no-jira

#3671 fix: build image for rte
  Dockerfile
Labels: no-jira
