Repository toptal/picasso, pull requests merged in 2023-03, with the labels that each got.

#3403 Version Packages
  .changeset/shiny-cooks-flow.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3404 Version Packages
  .changeset/long-snakes-walk.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3405 fix: changelog file
  .changeset/stupid-moose-decide.md
  packages/picasso-pictograms/CHANGELOG.md
Labels: no-jira

#3406 Version Packages
  .changeset/stupid-moose-decide.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3409 Version Packages
  .changeset/happy-humans-repair.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3411 Version Packages
  .changeset/proud-avocados-yawn.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3413 Version Packages
  .changeset/strong-meals-play.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3415 Version Packages
  .changeset/quick-ways-learn.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3419 chore(deps): bump json5
  package.json
  yarn.lock
Labels: dependencies, security, no-jira

#3417 chore: add DeveloperExpert pictogram
  .changeset/fluffy-ghosts-carry.md
  packages/picasso-pictograms/src/Pictogram/DeveloperExpertBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/index.ts
  packages/picasso-pictograms/src/Pictogram/svg/DeveloperExpertBlue64.svg
Labels: contribution

#3423 Version Packages
  .changeset/angry-pumpkins-move.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3418 chore(deps): bump recharts
  .changeset/big-cows-run.md
  packages/picasso-charts/package.json
  packages/picasso-charts/src/BarChart/BarChart.tsx
  packages/picasso-charts/src/LineChart/LineChart.tsx
  packages/picasso-charts/src/types.ts
  packages/picasso-charts/src/utils/calculate-tooltip-position/calculate-tooltip-position.ts
  yarn.lock
Labels: dependencies, security, no-jira

#3424 Version Packages
  .changeset/big-cows-run.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3427 feat(Icon): add VerificationBadge icons
  .changeset/two-cheetahs-cheer.md
  packages/picasso/src/Icon/VerificationBadge16.tsx
  packages/picasso/src/Icon/VerificationBadge24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/verificationBadge16.svg
  packages/picasso/src/Icon/svg/verificationBadge24.svg
Labels: contribution

#3428 Version Packages
  .changeset/two-cheetahs-cheer.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3440 Version Packages
  .changeset/lovely-dingos-tease.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3441 fix: increase timeout for build-image
  ci/jobs/build-image/Jenkinsfile
Labels: no-jira

#3443 Version Packages
  .changeset/add-icons.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3456 Version Packages
  .changeset/fifty-keys-sit.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3459 Version Packages
  .changeset/neat-icons-end.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3460 Version Packages
  .changeset/calm-kiwis-taste.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3464 fix: use proper version of reused GHA
  .github/workflows/davinci-alpha-package.yml
Labels: no-jira

#3465 Version Packages
  .changeset/chilled-steaks-marry.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3469 Version Packages
  .changeset/swift-pears-sleep.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3471 Version Packages
  .changeset/hot-ligers-invent.md
  .changeset/many-spies-share.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
