Repository toptal/picasso, pull requests merged in 2023-07, with the labels that each got.

#3675 docs: add RFC for bar indicators in bar chart
  docs/decisions/17-bar-indicators-for-barchart.md
Labels: docs, contribution

#3673 feat(barchart): add option to customize a bar indicator
  .changeset/modern-brooms-sing.md
  cypress/component/BarChart.spec.tsx
  packages/picasso-charts/src/BarChart/BarChart.tsx
  packages/picasso-charts/src/BarChart/story/BarIndicator.example.tsx
  packages/picasso-charts/src/BarChart/story/index.jsx
  packages/picasso-charts/src/BarChartIndicator/BarChartIndicator.tsx
  packages/picasso-charts/src/BarChartIndicator/index.ts
  packages/picasso-charts/src/BarChartIndicators/BarChartIndicators.tsx
  packages/picasso-charts/src/BarChartIndicators/index.ts
  packages/picasso-charts/src/index.ts
  packages/picasso-charts/src/types.ts
Labels: contribution

#3695 Version Packages
  .changeset/modern-brooms-sing.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3699 chore: remove test
  cypress/component/RichTextEditor.spec.tsx
Labels: no-jira

#3703 Version Packages
  .changeset/honest-windows-dream.md
  .changeset/hungry-rice-remember.md
  .changeset/orange-taxis-sell.md
  .changeset/perfect-spies-clean.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3709 Version Packages
  .changeset/blue-pugs-sleep.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3719 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-jira

#3720 fix: use fixed month for Calendar stories
  packages/picasso/src/Calendar/story/WithTwoMonths.example.tsx
  packages/picasso/src/Calendar/story/WithWeekStartsOnSunday.example.tsx
Labels: no-jira

#3712 Version Packages
  .changeset/curvy-bananas-live.md
  .changeset/eleven-guests-jam.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3721 Version Packages
  .changeset/hot-hounds-rhyme.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3722 Version Packages
  .changeset/fifty-pugs-travel.md
  .changeset/good-actors-glow.md
  .changeset/tender-kangaroos-shout.md
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3730 Version Packages
  .changeset/fresh-suns-hang.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3734 fix: job name
  .github/workflows/ci.yaml
Labels: no-jira

#3740 chore: fix Form backend communication example story
  packages/picasso-forms/src/Form/story/BackendCommunication.example.tsx
Labels: no-jira

#3742 Version Packages
  .changeset/tiny-dodos-lie.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3744 fix: flaky test
  packages/picasso-rich-text-editor/src/RichText/story/HTML.example.tsx
Labels: no-jira

#3747 Version Packages
  .changeset/fast-bulldogs-study.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3749 Version Packages
  .changeset/three-spiders-doubt.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3750 Version Packages
  .changeset/itchy-coats-switch.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3752 chore: upgrade jira deployment version
  .github/workflows/ci.yaml
  .github/workflows/davinci-alpha-package.yml
  .github/workflows/release.yml
Labels: no-jira

#3753 Version Packages
  .changeset/sour-bees-tie.md
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3754 Version Packages
  .changeset/long-carpets-care.md
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3760 Version Packages
  .changeset/tame-coins-breathe.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
