Repository toptal/picasso, pull requests merged in 2023-04, with the labels that each got.

#3476 Version Packages
  .changeset/bright-kids-cheat.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3461 fix(Pictograms): enable side-effects: false
  .changeset/silent-lamps-arrive.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3481 Version Packages
  .changeset/silent-lamps-arrive.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3480 fix: set static date for visual tests
  packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx
Labels: no-jira

#3468 feat(BarChart): add vertical layout
  .changeset/warm-rivers-beg.md
  cypress/component/BarChart.spec.tsx
  packages/picasso-charts/src/BarChart/BarChart.tsx
  packages/picasso-charts/src/BarChart/story/VerticalBar.example.tsx
  packages/picasso-charts/src/BarChart/story/index.jsx
  packages/picasso-charts/src/types.ts
Labels: no-jira, contribution

#3489 Version Packages
  .changeset/fifty-glasses-develop.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3497 fix: class names creator in PicassoLight
  .changeset/five-meals-appear.md
  packages/picasso-provider/src/Picasso/PicassoLight/PicassoLight.tsx
Labels: no-jira

#3491 Version Packages
  .changeset/five-meals-appear.md
  .changeset/gold-knives-enjoy.md
  .changeset/metal-lies-deny.md
  .changeset/nervous-clouds-shake.md
  .changeset/shiny-flowers-trade.md
  .changeset/stupid-pens-tease.md
  .changeset/sweet-emus-punch.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3502 Version Packages
  .changeset/five-meals-appear.md
  .changeset/gold-knives-enjoy.md
  .changeset/metal-lies-deny.md
  .changeset/nervous-clouds-shake.md
  .changeset/shiny-flowers-trade.md
  .changeset/stupid-pens-tease.md
  .changeset/sweet-emus-punch.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3503 Version Packages
  .changeset/ten-eyes-poke.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3506 fix(Stepper): always show active Step's StepLabel
  .changeset/little-pillows-clean.md
  packages/picasso/src/StepLabel/StepLabel.tsx
  packages/picasso/src/StepLabel/styles.ts
  packages/picasso/src/Stepper/__snapshots__/test.tsx.snap
  packages/picasso/src/StepperVertical/__snapshots__/test.tsx.snap
Labels: Bugfix, contribution

#3508 Version Packages
  .changeset/little-pillows-clean.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3504 feat(Icon): add new `flag` and `leadOrgUnitJoin` icons from BASE
  .changeset/modern-oranges-travel.md
  packages/picasso/src/Icon/Flag16.tsx
  packages/picasso/src/Icon/Flag24.tsx
  packages/picasso/src/Icon/LeadOrgUnitJoin16.tsx
  packages/picasso/src/Icon/LeadOrgUnitJoin24.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/flag16.svg
  packages/picasso/src/Icon/svg/flag24.svg
  packages/picasso/src/Icon/svg/leadOrgUnitJoin16.svg
  packages/picasso/src/Icon/svg/leadOrgUnitJoin24.svg
Labels: icon, contribution

#3514 Version Packages
  .changeset/modern-oranges-travel.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3510 feat: add className property to PageHead components
  .changeset/fair-tables-heal.md
  packages/picasso/src/PageHead/PageHead.tsx
Labels: contribution

#3517 Version Packages
  .changeset/fair-tables-heal.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3516 test: update BarChart visual test to remove flaky test
  cypress/component/BarChart.spec.tsx
Labels: no-jira

#3509 feat: support emojis and custom emojis in richtexteditor
  .changeset/selfish-kids-boil.md
  @types/quill-emoji/index.d.ts
  package.json
  packages/picasso/package.json
  packages/picasso/src/QuillEditor/QuillEditor.tsx
  packages/picasso/src/QuillEditor/blots/emoji.ts
  packages/picasso/src/QuillEditor/constants.ts
  packages/picasso/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
  packages/picasso/src/QuillEditor/hooks/useSubscribeToTextEditorEvents/useSubscribeToTextEditorEvents.tsx
  packages/picasso/src/QuillEditor/types.ts
  packages/picasso/src/QuillEditorView/styles.ts
  packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
  packages/picasso/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso/src/RichTextEditor/hooks/useToolbarHandlers/useToolbarHandlers.tsx
  packages/picasso/src/RichTextEditor/index.ts
  packages/picasso/src/RichTextEditor/story/Emoji.example.tsx
  packages/picasso/src/RichTextEditor/story/index.jsx
  packages/picasso/src/RichTextEditor/types.ts
  packages/picasso/src/RichTextEditorButton/RichTextEditorButton.tsx
  packages/picasso/src/RichTextEditorEmojiPicker/RichTextEditorEmojiPicker.tsx
  packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
  packages/picasso/src/utils/html-to-hast.ts
  yarn.lock
Labels: Feature, contribution

#3519 Version Packages
  .changeset/selfish-kids-boil.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3520 fix: reset button when datepicker calendar is closed
  .changeset/chatty-sheep-watch.md
  packages/picasso/src/DatePicker/DatePicker.tsx
  packages/picasso/src/DatePicker/test.tsx
Labels: Bugfix, contribution

#3521 Version Packages
  .changeset/chatty-sheep-watch.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3524 chore: make prop table responsive in Picasso Storybook
  .storybook/components/PicassoBook/components/PropsTable/styles.ts
  .storybook/preview-head.html
Labels: no-jira

#3530 Version Packages
  .changeset/cold-teachers-refuse.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
