Repository toptal/picasso, pull requests merged in 2023-05, with the labels that each got.

#3536 fix: breakpoints docs
  docs/decisions/13-breakpoints.md
Labels: no-jira

#3537 fix(RichTextEditor): default value not populated
  packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx
Labels: no-jira, docs, contribution

#3555 Version Packages
  .changeset/gentle-taxis-hammer.md
  .changeset/kind-clocks-film.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3557 Version Packages
  .changeset/moody-cooks-walk.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3559 Version Packages
  .changeset/brave-eyes-raise.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3563 Version Packages
  .changeset/few-seahorses-clap.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3566 Version Packages
  .changeset/brave-snails-accept.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3565 fix(Drawer): close button and standard title overlap
  .changeset/shiny-files-peel.md
  packages/picasso/src/DrawerTitle/styles.ts
Labels: contribution

#3569 Version Packages
  .changeset/shiny-files-peel.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3572 Version Packages
  .changeset/calm-students-refuse.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3573 chore: add ShareLink pictogram
  .changeset/afraid-dancers-allow.md
  packages/picasso-pictograms/src/Pictogram/ShareLinkBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/index.ts
  packages/picasso-pictograms/src/Pictogram/svg/ShareLinkBlue64.svg
Labels: contribution

#3575 Version Packages
  .changeset/afraid-dancers-allow.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#3571 chore: add light blue color in indicator
  .changeset/tender-insects-accept.md
  packages/picasso/src/Indicator/Indicator.tsx
  packages/picasso/src/Indicator/story/Default.example.tsx
  packages/picasso/src/Indicator/styles.ts
  packages/picasso/src/TagRectangular/story/Indicators.example.tsx
Labels: contribution

#3576 Version Packages
  .changeset/tender-insects-accept.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3577 fix: pixel gap problem
  .changeset/light-pandas-explain.md
  packages/picasso-provider/src/Picasso/config/breakpoints.ts
  packages/picasso-provider/src/Picasso/config/test.ts
  yarn.lock
Labels: no-jira

#3582 Version Packages
  .changeset/light-pandas-explain.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3583 Version Packages
  .changeset/brown-bottles-sleep.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3585 Version Packages
  .changeset/calm-pumas-deny.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
