Repository toptal/picasso, pull requests merged in 2023-10, with the labels that each got.

#3908 Version Packages
  .changeset/stale-cherries-clap.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3909 Version Packages
  .changeset/dry-llamas-rest.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3921 Version Packages
  .changeset/curvy-squids-reply.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3930 fix: revert commit
  .storybook/main.js
  packages/picasso/src/Timeline/story/CustomDateColumn.example.tsx
  packages/picasso/src/Timeline/story/index.jsx
  packages/picasso/src/TimelineRow/TimelineRow.tsx
Labels: no-jira

#3926 fix(picasso-charts): fix BarChart for cases with 0 values
  .changeset/many-papayas-serve.md
  cypress/component/BarChart.spec.tsx
  packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts
Labels: contribution

#3932 Version Packages
  .changeset/many-papayas-serve.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3937 Version Packages
  .changeset/poor-papayas-brake.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira

#3938 Version Packages
  .changeset/sour-tools-admire.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3939 chore: collapse accordion in story for visual tests
  packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
Labels: no-jira, contribution

#3944 Version Packages
  .changeset/two-foxes-type.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3947 chore: add integration tests for query builder
  cypress/component/QueryBuilder/QueryBuilder.spec.tsx
  packages/picasso-query-builder/src/AddGroupButton/AddGroupButton.tsx
  packages/picasso-query-builder/src/AutoComplete/AutoComplete.tsx
  packages/picasso-query-builder/src/FieldSelector/FieldSelector.tsx
  packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
  packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
  packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
  packages/picasso-query-builder/src/RunQueryButton/RunQueryButton.tsx
  packages/picasso-query-builder/src/Select/Select.tsx
  packages/picasso-query-builder/src/TextInput/TextInput.tsx
  packages/picasso-query-builder/src/ValueEditor/ValueEditor.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
Labels: contribution
