Repository toptal/picasso, pull requests merged in 2023-01, with the labels that each got.

#3308 chore: extract stateful code from AvatarUpload to hooks
  packages/picasso/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso/src/AvatarUpload/hooks/use-avatar-states/index.ts
  packages/picasso/src/AvatarUpload/hooks/use-avatar-states/test.ts
  packages/picasso/src/AvatarUpload/hooks/use-avatar-states/useAvatarStates.ts
  packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/index.ts
  packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/test.ts
  packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/useAvatarUpload.ts
Labels: Chore

#3319 Version Packages
  .changeset/shy-pets-accept.md
  .changeset/two-lamps-jam.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#3318 feat(Drawer): add body scroll lock
  .changeset/nice-donuts-check.md
  packages/picasso/src/Drawer/Drawer.tsx
  packages/picasso/src/Drawer/story/WithBodyScrollLock.example.tsx
  packages/picasso/src/Drawer/story/index.jsx
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/utils/Modal/modal-manager.ts
  packages/picasso/src/utils/__tests__/use-body-scroll-lock.test.tsx
  packages/picasso/src/utils/use-body-scroll-lock.ts
Labels: contribution

#3320 Version Packages
  .changeset/nice-donuts-check.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3325 Version Packages
  .changeset/shiny-fans-learn.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3327 chore(Sidebar): introduce `onCollapse` callback
  .changeset/pink-experts-cheat.md
  packages/picasso/src/PageSidebar/PageSidebar.tsx
  packages/picasso/src/PageSidebar/story/Collapsible.example.tsx
Labels: contribution

#3328 Version Packages
  .changeset/pink-experts-cheat.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3326 chore(Modal): remove onBackdropClick and update onClose
  .changeset/forty-snails-compete.md
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/Modal/story/DisableBackdropClick.example.tsx
  packages/picasso/src/Modal/story/index.jsx
Labels: no-jira, contribution

#3330 Version Packages
  .changeset/forty-snails-compete.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3332 fix: import from material-ui's barrel module
  .changeset/angry-apricots-flow.md
  packages/picasso/src/Accordion/Accordion.tsx
  packages/picasso/src/AccordionDetails/AccordionDetails.tsx
  packages/picasso/src/AccordionSummary/AccordionSummary.tsx
  packages/picasso/src/ApplicationUpdateNotification/ApplicationUpdateNotification.tsx
  packages/picasso/src/Button/Button.tsx
  packages/picasso/src/Checkbox/Checkbox.tsx
  packages/picasso/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso/src/Chip/index.ts
  packages/picasso/src/CircularProgress/CircularProgress.tsx
  packages/picasso/src/Drawer/Drawer.tsx
  packages/picasso/src/Grid/Grid.tsx
  packages/picasso/src/GridItem/GridItem.tsx
  packages/picasso/src/InputAdornment/InputAdornment.tsx
  packages/picasso/src/InputLabel/InputLabel.tsx
  packages/picasso/src/Link/Link.tsx
  packages/picasso/src/Menu/Menu.tsx
  packages/picasso/src/MenuItem/MenuItem.tsx
  packages/picasso/src/Modal/Modal.tsx
  packages/picasso/src/NativeSelect/NativeSelect.tsx
  packages/picasso/src/Notification/Notification.tsx
  packages/picasso/src/NumberInputEndAdornment/NumberInputEndAdornment.tsx
  packages/picasso/src/OutlinedInput/OutlinedInput.tsx
  packages/picasso/src/Paper/Paper.tsx
  packages/picasso/src/Popover/index.ts
  packages/picasso/src/Popper/Popper.tsx
  packages/picasso/src/Radio/Radio.tsx
  packages/picasso/src/RadioGroup/RadioGroup.tsx
  packages/picasso/src/Slider/Slider.tsx
  packages/picasso/src/Step/Step.tsx
  packages/picasso/src/Stepper/Stepper.tsx
  packages/picasso/src/Switch/Switch.tsx
  packages/picasso/src/Tab/Tab.tsx
  packages/picasso/src/Table/Table.tsx
  packages/picasso/src/TableBody/TableBody.tsx
  packages/picasso/src/TableCell/TableCell.tsx
  packages/picasso/src/TableExpandableRow/TableExpandableRow.tsx
  packages/picasso/src/TableFooter/TableFooter.tsx
  packages/picasso/src/TableHead/TableHead.tsx
  packages/picasso/src/TableRow/TableRow.tsx
  packages/picasso/src/Tabs/Tabs.tsx
  packages/picasso/src/Tooltip/Tooltip.tsx
  packages/picasso/src/Typography/Typography.tsx
Labels: contribution

#3333 Version Packages
  .changeset/angry-apricots-flow.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3331 fix(RichTextEditor): when disabled it shows defaultValue
  .changeset/flat-beans-kick.md
  packages/picasso/src/QuillEditor/QuillEditor.tsx
  packages/picasso/src/QuillEditor/hooks/useDisabledEditor/test.ts
  packages/picasso/src/RichTextEditor/story/Disabled.example.tsx
Labels: contribution

#3334 Version Packages
  .changeset/flat-beans-kick.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3337 feat: export TagRectangular VariantType on main package
  .changeset/tricky-ears-retire.md
  packages/picasso/src/TagRectangular/index.ts
  packages/picasso/src/index.ts
Labels: no-jira

#3339 Version Packages
  .changeset/tricky-ears-retire.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3342 Version Packages
  .changeset/fair-deers-breathe.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3344 Version Packages
  .changeset/neat-pianos-allow.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3348 Version Packages
  .changeset/pretty-suits-beg.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3349 Version Packages
  .changeset/ninety-scissors-cheat.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
