Repository toptal/picasso, pull requests merged in 2023-12, with the labels that each got.

#4043 Version Packages
  .changeset/large-olives-fly.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#4046 Version Packages
  .changeset/early-glasses-fry.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#4047 [CPT-1489] Add data-testid to ValidationErrors in QueryBuilder
  .changeset/purple-onions-glow.md
  packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
  packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
  packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
  yarn.lock
Labels: contribution

#4049 Version Packages
  .changeset/purple-onions-glow.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira

#4057 Version Packages
  .changeset/stale-geese-carry.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#4059 Version Packages
  .changeset/tidy-jokes-end.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#4060 Version Packages
  .changeset/strange-squids-retire.md
  packages/picasso-tailwind/CHANGELOG.md
  packages/picasso-tailwind/package.json
Labels: no-jira

#4066 Version Packages
  .changeset/lemon-chairs-compare.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4067 Fix data-private type to allow lipsum value
  .changeset/tidy-crabs-hammer.md
  packages/shared/src/types.ts
Labels: no-jira, contribution

#4069 Version Packages
  .changeset/tidy-crabs-hammer.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira
