Repository toptal/picasso, pull requests merged in 2023-11, with the labels that each got.

#3948 fix(section): correct type condition for subtitle
  .changeset/orange-falcons-fix.md
  packages/picasso/src/Section/Section.tsx
Labels: Bugfix

#3950 Version Packages
  .changeset/orange-falcons-fix.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3952 Version Packages
  .changeset/curvy-papayas-explain.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3953 chore: move url-generator util
  .storybook/components/PicassoBook/Chapter.tsx
  .storybook/utils/url-generator.ts
Labels: no-jira

#3958 Version Packages
  .changeset/witty-bees-impress.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3959 Version Packages
  .changeset/twenty-eagles-breathe.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira

#3964 Version Packages
  .changeset/blue-tables-vanish.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3960 chore: update ownership of query builder
  .github/CODEOWNERS
Labels: contribution

#3966 feat: [SCR-X] Implements custom stepper content
  .changeset/green-carrots-battle.md
  packages/picasso/src/StepLabel/StepLabel.tsx
  packages/picasso/src/Stepper/Stepper.tsx
  packages/picasso/src/Stepper/__snapshots__/test.tsx.snap
  packages/picasso/src/Stepper/story/Default.example.tsx
  packages/picasso/src/Stepper/test.tsx
Labels: no-jira, contribution

#3985 Version Packages
  .changeset/twenty-squids-tell.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
Labels: no-jira

#3986 [FX-4497] Add PostCSS to resolutions to fix vulnerability
  package.json
  yarn.lock
Labels: dependencies, security

#3989 ci: fix alpha packages
  .github/workflows/davinci-alpha-package.yml
Labels: no-jira, contribution

#3991 [FX-4497] Bump davinci packages to fix axios vulnerability
  package.json
  yarn.lock
Labels: dependencies, security

#4001 Provide token to pr-conventional-to-toptal-commits
  .github/workflows/format-dependabot-prs.yml
Labels: no-jira

#4004 Replace external proxy with IAP
  .github/workflows/release.yml
Labels: no-jira

#4005 Revert IAP changes and fix proxy
  .github/workflows/release.yml
Labels: no-jira, contribution

#4006 Version Packages
  .changeset/clean-yaks-punch.md
  .changeset/few-deers-care.md
  .changeset/lovely-pumpkins-help.md
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4008 Fix picasso-tailwind package.json exports
  .changeset/hip-lions-invite.md
  packages/picasso-tailwind/package.json
Labels: no-jira

#4009 [FX-4497] Update davinci dependencies
  package.json
  yarn.lock
Labels: dependencies, security

#4007 Version Packages
  .changeset/hip-lions-invite.md
  .changeset/rich-moose-glow.md
  packages/picasso-tailwind/CHANGELOG.md
  packages/picasso-tailwind/package.json
Labels: no-jira

#4013 Let HTTP_PROXY only on necessary locations
  .github/workflows/ci.yaml
Labels: no-jira

#4015 Version Packages
  .changeset/red-tigers-join.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#4020 Version Packages
  .changeset/pink-carrots-protect.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4014 [CI-X] Replace external proxy with IAP
  .changeset/funny-snakes-pull.md
  .github/workflows/ci.yaml
  .github/workflows/release.yml
Labels: CI, no-jira, contribution

#4026 Version Packages
  .changeset/funny-snakes-pull.md
  .changeset/perfect-apricots-buy.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4030 Version Packages
  .changeset/heavy-seals-sneeze.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4034 Version Packages
  .changeset/smooth-pillows-notice.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4035 Version Packages
  .changeset/loud-geese-destroy.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#4036 Version Packages
  .changeset/brown-pigs-tie.md
  .changeset/neat-lies-mate.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
