Repository toptal/picasso, pull requests merged in 2023-09, with the labels that each got.

#3841 Version Packages
  .changeset/chatty-rice-design.md
  .changeset/eleven-games-occur.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3837 fix(rich-text-editor): enable alt prop
  .changeset/gold-frogs-itch.md
  packages/picasso-rich-text-editor/src/utils/html-to-hast.ts
Labels: Bugfix, contribution

#3844 Version Packages
  .changeset/gold-frogs-itch.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3849 Version Packages
  .changeset/blue-dodos-allow.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#3851 Version Packages
  .changeset/rotten-experts-taste.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3853 ci(Dockerfile): remove setting of alpine mirror
  Dockerfile
Labels: no-jira

#3854 ci: upgrade create-jira-deployment version
  .github/workflows/ci.yaml
  .github/workflows/davinci-alpha-package.yml
  .github/workflows/release.yml
Labels: no-jira, contribution

#3859 Version Packages
  .changeset/swift-bugs-sparkle.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3860 fix: revert accidental push
  .changeset/thick-dolls-heal.md
  packages/picasso-forms/package.json
  yarn.lock
Labels: no-jira

#3861 fix: revert dependency update
  .changeset/random-changeset-name.md
  packages/picasso-forms/package.json
  yarn.lock
Labels: no-jira

#3862 Version Packages
  .changeset/random-changeset-name.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3863 feat: update twitter icon
  .changeset/cyan-pugs-decide.md
  packages/picasso/src/Icon/Twitter16.tsx
  packages/picasso/src/Icon/Twitter24.tsx
  packages/picasso/src/Icon/svg/twitter16.svg
  packages/picasso/src/Icon/svg/twitter24.svg
Labels: contribution

#3865 Version Packages
  .changeset/cyan-pugs-decide.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3867 Version Packages
  .changeset/shaggy-paws-hide.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3876 Version Packages
  .changeset/neat-impalas-notice.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3873 feat(icons): add employee icons
  .changeset/swift-fireants-float.md
  packages/picasso/src/Icon/Employee16.tsx
  packages/picasso/src/Icon/Employee24.tsx
  packages/picasso/src/Icon/EmployeeResponsive.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/employee16.svg
  packages/picasso/src/Icon/svg/employee24.svg
Labels: icon, contribution

#3877 Version Packages
  .changeset/swift-fireants-float.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3878 fix: lockfile
  yarn.lock
Labels: no-jira

#3881 Version Packages
  .changeset/fast-eagles-refuse.md
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3855 fix(FieldLabel): form label rendering
  .changeset/fresh-crabs-laugh.md
  packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
Labels: no-jira, contribution

#3882 Version Packages
  .changeset/fresh-crabs-laugh.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#3885 Version Packages
  .changeset/tall-countries-push.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#3891 Version Packages
  .changeset/gold-toys-unite.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira

#3894 Version Packages
  .changeset/good-houses-end.md
  .changeset/grey-back-whale.md
  .changeset/metal-lions-move.md
  .changeset/quiet-buckets-love.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#3896 Version Packages
  .changeset/long-rice-cheer.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3901 Version Packages
  .changeset/grumpy-toes-cry.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3899 chore(deps): add yaml to resolutions to remove vulnerability
  package.json
  yarn.lock
Labels: dependencies, security, no-jira

#3902 Version Packages
  .changeset/tender-boxes-marry.md
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/package.json
  packages/shared/package.json
Labels: no-jira
