Repository toptal/picasso, pull requests merged in 2023-02, with the labels that each got.

#3357 fix: workflow typo
  .github/workflows/davinci-integration-tests.yml
Labels: no-jira

#3350 Version Packages
  .changeset/chilly-clocks-explode.md
  .changeset/fifty-flies-try.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3355 test: remove flaky test
  cypress/component/Menu.spec.tsx
Labels: no-jira

#3365 feat(Select): introduce new filterOptions prop
  .changeset/brown-phones-worry.md
  packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
  packages/picasso/src/NonNativeSelect/test.tsx
  packages/picasso/src/Select/story/FilterOptions.example.tsx
  packages/picasso/src/Select/story/index.jsx
  packages/picasso/src/SelectBase/hooks/use-select-state/use-select-state.ts
  packages/picasso/src/SelectBase/types.ts
  packages/picasso/src/SelectBase/utils/filter-options/filter-options.ts
  packages/picasso/src/SelectBase/utils/filter-options/index.ts
  packages/picasso/src/SelectBase/utils/index.ts
Labels: no-jira, contribution

#3367 chore: add missing changeset
  .changeset/silly-donkeys-lick.md
Labels: no-jira

#3368 Version Packages
  .changeset/brown-phones-worry.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3360 chore(Dropdown): add comment for placement prop
  .changeset/quick-ducks-hammer.md
  packages/picasso/src/Dropdown/Dropdown.tsx
Labels: no-jira, contribution

#3371 Version Packages
  .changeset/quick-ducks-hammer.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3372 chore: update to davinci qa in ESM
  cypress.config.mjs
  jest.spec.mjs
  package.json
  yarn.lock
Labels: no-jira

#3378 feat(Tabs): add variant prop
  .changeset/small-dolls-jam.md
  packages/picasso/src/Tabs/Tabs.tsx
  packages/picasso/src/Tabs/__snapshots__/test.tsx.snap
  packages/picasso/src/Tabs/story/FullWidth.example.tsx
  packages/picasso/src/Tabs/story/index.jsx
  packages/picasso/src/Tabs/test.tsx
Labels: Feature, contribution

#3379 fix(calendar): add disabled attribute & default cursor to disabled days
  .changeset/afraid-clocks-shave.md
  packages/picasso/src/Calendar/Calendar.tsx
  packages/picasso/src/Calendar/styles.ts
Labels: Bugfix, contribution

#3383 Version Packages
  .changeset/afraid-clocks-shave.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3385 Version Packages
  .changeset/green-games-count.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#3392 fix: typings for Tabs onChange callback
  .changeset/twelve-shrimps-obey.md
  packages/picasso/src/Tabs/Tabs.tsx
  packages/picasso/src/Tabs/test.tsx
Labels: contribution

#3393 Version Packages
  .changeset/twelve-shrimps-obey.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3400 Version Packages
  .changeset/nervous-chicken-trade.md
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#3395 fix(datepicker): revert calendar disabled attribute to allow render tooltips
  .changeset/three-spiders-sit.md
  packages/picasso/src/Calendar/Calendar.tsx
Labels: Bugfix, contribution

#3402 Version Packages
  .changeset/nine-cycles-turn.md
  packages/picasso-codemod/CHANGELOG.md
  packages/picasso-codemod/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira
