Repository toptal/picasso, pull requests merged in 2024-06, with the labels that each got.

#4346 [COMM-3443] Add warning and critical icons
  .changeset/thirty-colts-boil.md
  packages/base/Icons/src/Icon/Critical16.tsx
  packages/base/Icons/src/Icon/Critical24.tsx
  packages/base/Icons/src/Icon/CriticalResponsive.tsx
  packages/base/Icons/src/Icon/CriticalSolid16.tsx
  packages/base/Icons/src/Icon/CriticalSolid24.tsx
  packages/base/Icons/src/Icon/CriticalSolidResponsive.tsx
  packages/base/Icons/src/Icon/Warning16.tsx
  packages/base/Icons/src/Icon/Warning24.tsx
  packages/base/Icons/src/Icon/WarningResponsive.tsx
  packages/base/Icons/src/Icon/WarningSolid16.tsx
  packages/base/Icons/src/Icon/WarningSolid24.tsx
  packages/base/Icons/src/Icon/WarningSolidResponsive.tsx
  packages/base/Icons/src/Icon/index.ts
  packages/base/Icons/src/Icon/story/index.jsx
  packages/base/Icons/src/Icon/svg/critical16.svg
  packages/base/Icons/src/Icon/svg/critical24.svg
  packages/base/Icons/src/Icon/svg/criticalSolid16.svg
  packages/base/Icons/src/Icon/svg/criticalSolid24.svg
  packages/base/Icons/src/Icon/svg/warning16.svg
  packages/base/Icons/src/Icon/svg/warning24.svg
  packages/base/Icons/src/Icon/svg/warningSolid16.svg
  packages/base/Icons/src/Icon/svg/warningSolid24.svg
Labels: contribution

#4337 Fix TagGroup to not take all space
  .changeset/famous-pets-know.md
  packages/base/Tag/src/TagGroup/TagGroup.tsx
  packages/base/Tag/src/TagGroup/__snapshots__/test.tsx.snap
  packages/base/Tag/src/TagGroup/styles.ts
Labels: no-jira

#4350 Version Packages
  .changeset/famous-pets-know.md
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Tag/CHANGELOG.md
  packages/base/Tag/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4296 [CI-3421] Move Trigger build image job step to GHA
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  Dockerfile
  ci/jobs/build-image/Jenkinsfile
Labels: contribution

#4358 [ARM-5353] Add some pictograms
  .changeset/calm-toes-deliver.md
  packages/picasso-pictograms/src/Pictogram/Clock2Blue64.tsx
  packages/picasso-pictograms/src/Pictogram/Clock2White64.tsx
  packages/picasso-pictograms/src/Pictogram/HandDeliveryBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/HandDeliveryWhite64.tsx
  packages/picasso-pictograms/src/Pictogram/ReportBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/ReportWhite64.tsx
  packages/picasso-pictograms/src/Pictogram/TeamBusinessBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/TeamBusinessWhite64.tsx
  packages/picasso-pictograms/src/Pictogram/TeamOkrsBlue64.tsx
  packages/picasso-pictograms/src/Pictogram/TeamOkrsWhite64.tsx
  packages/picasso-pictograms/src/Pictogram/index.ts
  packages/picasso-pictograms/src/Pictogram/svg/Clock2Blue64.svg
  packages/picasso-pictograms/src/Pictogram/svg/Clock2White64.svg
  packages/picasso-pictograms/src/Pictogram/svg/HandDeliveryBlue64.svg
  packages/picasso-pictograms/src/Pictogram/svg/HandDeliveryWhite64.svg
  packages/picasso-pictograms/src/Pictogram/svg/ReportBlue64.svg
  packages/picasso-pictograms/src/Pictogram/svg/ReportWhite64.svg
  packages/picasso-pictograms/src/Pictogram/svg/TeamBusinessBlue64.svg
  packages/picasso-pictograms/src/Pictogram/svg/TeamBusinessWhite64.svg
  packages/picasso-pictograms/src/Pictogram/svg/TeamOkrsBlue64.svg
  packages/picasso-pictograms/src/Pictogram/svg/TeamOkrsWhite64.svg
Labels: contribution

#4361 Version Packages
  .changeset/calm-toes-deliver.md
  packages/picasso-pictograms/CHANGELOG.md
  packages/picasso-pictograms/package.json
Labels: no-jira

#4364 [TRN-6584] Add Control icon
  .changeset/spicy-hats-move.md
  README.md
  packages/base/Icons/src/Icon/Control16.tsx
  packages/base/Icons/src/Icon/Control24.tsx
  packages/base/Icons/src/Icon/ControlResponsive.tsx
  packages/base/Icons/src/Icon/index.ts
  packages/base/Icons/src/Icon/svg/control16.svg
  packages/base/Icons/src/Icon/svg/control24.svg
Labels: icon, contribution

#4373 Version Packages
  .changeset/tough-ties-hear.md
  packages/base/TreeView/CHANGELOG.md
  packages/base/TreeView/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4375 [TOP-4660] Update exports
  .changeset/little-bobcats-draw.md
  packages/base/Select/src/index.ts
  packages/picasso/src/index.ts
Labels: contribution

#4379 [TOP-4660] Fix SelectCaret export
  .changeset/red-chairs-smoke.md
  packages/base/Select/src/NativeSelect/NativeSelect.tsx
  packages/base/Select/src/NonNativeSelect/NonNativeSelect.tsx
  packages/base/Select/src/SelectCaret/index.tsx
Labels: contribution

#4381 Version Packages
  .changeset/red-chairs-smoke.md
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4372 Fix button errors
  .changeset/angry-colts-scream.md
  packages/base/Button/src/ButtonAction/ButtonAction.tsx
  packages/base/Button/src/ButtonBase/ButtonBase.tsx
  packages/base/Button/src/ButtonControlLabel/ButtonControlLabel.tsx
Labels: no-jira

#4357 [TI-2599] Add placement prop to TypographyOverflow component
  .changeset/olive-foxes-perform.md
  packages/base/TypographyOverflow/src/TypographyOverflow/TypographyOverflow.tsx
  packages/base/TypographyOverflow/src/TypographyOverflow/story/Placement.example.tsx
  packages/base/TypographyOverflow/src/TypographyOverflow/story/index.jsx
Labels: contribution, Talent Insights

#4383 Version Packages
  .changeset/fast-ligers-exercise.md
  .changeset/olive-foxes-perform.md
  .changeset/plenty-keys-guess.md
  packages/base/Drawer/CHANGELOG.md
  packages/base/Drawer/package.json
  packages/base/Dropzone/CHANGELOG.md
  packages/base/Dropzone/package.json
  packages/base/FileInput/CHANGELOG.md
  packages/base/FileInput/package.json
  packages/base/Step/CHANGELOG.md
  packages/base/Step/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/TypographyOverflow/CHANGELOG.md
  packages/base/TypographyOverflow/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4387 Revert davinci-github-actions/build-push-image update
  .github/workflows/ci.yaml
  .github/workflows/release.yml
Labels: no-jira

#4392 Version Packages
  .changeset/calm-peas-compare.md
  packages/base/Step/CHANGELOG.md
  packages/base/Step/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4393 Version Packages
  .changeset/calm-trainers-taste.md
  packages/base/Drawer/CHANGELOG.md
  packages/base/Drawer/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
