Repository toptal/picasso, pull requests merged in 2024-08, with the labels that each got.

#4432 [TI-2735] Add DesignerPencil16, DesignerPencil24, productManager16 and productManager24 icons
  .changeset/four-students-dress.md
  packages/base/Icons/src/Icon/DesignerPencil16.tsx
  packages/base/Icons/src/Icon/DesignerPencil24.tsx
  packages/base/Icons/src/Icon/DesignerPencilResponsive.tsx
  packages/base/Icons/src/Icon/ProductManager16.tsx
  packages/base/Icons/src/Icon/ProductManager24.tsx
  packages/base/Icons/src/Icon/ProductManagerResponsive.tsx
  packages/base/Icons/src/Icon/index.ts
  packages/base/Icons/src/Icon/svg/designerPencil16.svg
  packages/base/Icons/src/Icon/svg/designerPencil24.svg
  packages/base/Icons/src/Icon/svg/productManager16.svg
  packages/base/Icons/src/Icon/svg/productManager24.svg
Labels: contribution

#4436 Version Packages
  .changeset/nice-brooms-film.md
  packages/base/DatePicker/CHANGELOG.md
  packages/base/DatePicker/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4440 Version Packages
  .changeset/wild-fans-pay.md
  packages/base/EmptyState/CHANGELOG.md
  packages/base/EmptyState/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4441 Version Packages
  .changeset/late-swans-taste.md
  packages/base/Carousel/CHANGELOG.md
  packages/base/Carousel/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4445 Version Packages
  .changeset/sharp-clouds-thank.md
  packages/base/Calendar/CHANGELOG.md
  packages/base/Calendar/package.json
  packages/base/DatePicker/CHANGELOG.md
  packages/base/DatePicker/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4450 Version Packages
  .changeset/pink-rings-suffer.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#4462 Version Packages
  .changeset/seven-flowers-retire.md
  packages/base-tailwind/CHANGELOG.md
  packages/base-tailwind/package.json
Labels: no-jira

#4463 Version Packages
  .changeset/pretty-bats-sniff.md
  packages/base/Dropzone/CHANGELOG.md
  packages/base/Dropzone/package.json
  packages/base/FileInput/CHANGELOG.md
  packages/base/FileInput/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4468 [FX-NULL] Fix storybook build
  Dockerfile
Labels: no-jira

#4469 Version Packages
  .changeset/five-pigs-chew.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
Labels: no-jira

#4474 Version Packages
  .changeset/green-schools-sparkle.md
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/base/DatePicker/CHANGELOG.md
  packages/base/DatePicker/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Input/CHANGELOG.md
  packages/base/Input/package.json
  packages/base/NumberInput/CHANGELOG.md
  packages/base/NumberInput/package.json
  packages/base/OutlinedInput/CHANGELOG.md
  packages/base/OutlinedInput/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/PasswordInput/CHANGELOG.md
  packages/base/PasswordInput/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/Timepicker/CHANGELOG.md
  packages/base/Timepicker/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4476 Version Packages
  .changeset/odd-monkeys-divide.md
  packages/base/NumberInput/CHANGELOG.md
  packages/base/NumberInput/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4477 Version Packages
  .changeset/few-jeans-itch.md
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/DatePicker/CHANGELOG.md
  packages/base/DatePicker/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Input/CHANGELOG.md
  packages/base/Input/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/Timepicker/CHANGELOG.md
  packages/base/Timepicker/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4481 Version Packages
  .changeset/smooth-ghosts-sort.md
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4484 Fix types for mui@4 tabs
  .changeset/slow-gifts-hang.md
  packages/base/Tabs/package.json
  packages/base/Tabs/src/Tabs/Tabs.tsx
  packages/base/Tabs/src/Tabs/test.tsx
Labels: no-jira

#4482 Version Packages
  .changeset/slow-gifts-hang.md
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4478 [CPT-1074] Add test for duplicating and removing groups in QB
  .changeset/lucky-pillows-thank.md
  cypress/component/QueryBuilder/QueryBuilder.spec.tsx
  packages/picasso-query-builder/src/CloneGroupButton/CloneGroupButton.tsx
  packages/picasso-query-builder/src/RemoveGroupButton/RemoveGroupButton.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
Labels: contribution

#4487 Version Packages
  .changeset/lucky-pillows-thank.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira

#4488 Version Packages
  .changeset/two-ties-count.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/Avatar/CHANGELOG.md
  packages/base/Avatar/package.json
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Image/CHANGELOG.md
  packages/base/Image/package.json
  packages/base/Menu/CHANGELOG.md
  packages/base/Menu/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/UserBadge/CHANGELOG.md
  packages/base/UserBadge/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4493 Version Packages
  .changeset/twelve-fans-invent.md
  packages/base/Quote/CHANGELOG.md
  packages/base/Quote/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4495 [CPT-1075] Add tests to remove and clone query builder rules
  .changeset/twelve-stingrays-nail.md
  cypress/component/QueryBuilder/QueryBuilder.spec.tsx
  packages/picasso-query-builder/src/CloneRuleButton/CloneRuleButton.tsx
  packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
Labels: contribution

#4498 Version Packages
  .changeset/angry-worms-stare.md
  .changeset/nasty-avocados-shop.md
  .changeset/twelve-stingrays-nail.md
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Pagination/CHANGELOG.md
  packages/base/Pagination/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4503 Version Packages
  .changeset/tasty-avocados-shop.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/UserBadge/CHANGELOG.md
  packages/base/UserBadge/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4505 Version Packages
  .changeset/light-eels-deny.md
  packages/base/List/CHANGELOG.md
  packages/base/List/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4507 Add security scan
  .github/workflows/security-secrets-scan.yaml
Labels: no-jira

#4508 Update micromatch to remove vulnerability
  .github/workflows/security-secrets-scan.yaml
  yarn.lock
Labels: dependencies, security, no-jira

#4509 Version Packages
  .changeset/quiet-cheetahs-collect.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/Avatar/CHANGELOG.md
  packages/base/Avatar/package.json
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Logo/CHANGELOG.md
  packages/base/Logo/package.json
  packages/base/Menu/CHANGELOG.md
  packages/base/Menu/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/UserBadge/CHANGELOG.md
  packages/base/UserBadge/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4502 [FX-NULL] Add Version Packages reminder
  .github/workflows/notify-about-pending-release-pull-requests.yaml
Labels: no-jira

#4513 Version Packages
  .changeset/lovely-zebras-destroy.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/Avatar/CHANGELOG.md
  packages/base/Avatar/package.json
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Menu/CHANGELOG.md
  packages/base/Menu/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/UserBadge/CHANGELOG.md
  packages/base/UserBadge/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4516 Version Packages
  .changeset/moody-buckets-nail.md
  packages/base/Rating/CHANGELOG.md
  packages/base/Rating/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
