Repository toptal/picasso, pull requests merged in 2024-02, with the labels that each got.

#4129 Adjust root folder in alpha gh action
  .github/workflows/davinci-alpha-package.yml
Labels: no-jira

#4141 [CRT-6946][FX-4808] Adjust form labels alignement
  .changeset/good-crabs-obey.md
  packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso-forms/src/Dropzone/Dropzone.tsx
  packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
  packages/picasso-forms/src/Form/story/Horizontal.example.tsx
  packages/picasso-forms/src/Input/Input.tsx
  packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
  packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso/src/FormField/styles.ts
  packages/picasso/src/FormLabel/FormLabel.tsx
  packages/picasso/src/FormLabel/styles.ts
Labels: contribution

#4143 Version Packages
  .changeset/good-crabs-obey.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4145 [TI-2268] Introduce quote icon
  .changeset/dull-jeans-dance.md
  packages/picasso/src/Icon/Quote16.tsx
  packages/picasso/src/Icon/Quote24.tsx
  packages/picasso/src/Icon/QuoteResponsive.tsx
  packages/picasso/src/Icon/index.ts
  packages/picasso/src/Icon/svg/quote16.svg
  packages/picasso/src/Icon/svg/quote24.svg
Labels: contribution, Talent Insights

#4147 Version Packages
  .changeset/dull-jeans-dance.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4146 Add BASE spacings to the theme config
  .changeset/tender-crabs-accept.md
  packages/picasso-tailwind/src/index.js
Labels: no-jira

#4148 Version Packages
  .changeset/tender-crabs-accept.md
  packages/picasso-tailwind/CHANGELOG.md
  packages/picasso-tailwind/package.json
Labels: no-jira

#4151 [TACO] Fix PasswordInput size prop
  .changeset/beige-clocks-float.md
  packages/picasso/src/PasswordInput/PasswordInput.tsx
  packages/picasso/src/PasswordInput/story/Sizes.example.tsx
  packages/picasso/src/PasswordInput/story/index.jsx
Labels: no-jira, contribution

#4153 Version Packages
  .changeset/beige-clocks-float.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4155 Prevent Form onSubmit rejections from being swallowed
  .changeset/tiny-games-remain.md
  packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
Labels: no-jira, contribution

#4156 Version Packages
  .changeset/tiny-games-remain.md
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
Labels: no-jira

#4157 Version Packages
  .changeset/twelve-singers-knock.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira
