Repository toptal/picasso, pull requests merged in 2024-03, with the labels that each got.

#4158 Fix TimePicker duplicate clock icons
  .changeset/flat-rats-search.md
  packages/picasso/src/TimePicker/styles.ts
Labels: no-jira, contribution

#4161 [CRT-7024] Introduce 'labelEndAdornment' prop for Label component
  .changeset/small-trainers-hug.md
  packages/base/Checkbox/src/Checkbox/Checkbox.tsx
  packages/base/Form/src/FormLabel/FormLabel.tsx
  packages/base/Form/src/FormLabel/__snapshots__/test.tsx.snap
  packages/base/Form/src/FormLabel/test.tsx
  packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
  packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
  packages/picasso-forms/src/Checkbox/Checkbox.tsx
  packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
  packages/picasso-forms/src/DatePicker/DatePicker.tsx
  packages/picasso-forms/src/Dropzone/Dropzone.tsx
  packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
  packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
  packages/picasso-forms/src/FieldWrapper/story/index.jsx
  packages/picasso-forms/src/FileInput/FileInput.tsx
  packages/picasso-forms/src/Form/Form.tsx
  packages/picasso-forms/src/Form/story/Horizontal.example.tsx
  packages/picasso-forms/src/Input/Input.tsx
  packages/picasso-forms/src/NumberInput/NumberInput.tsx
  packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
  packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
  packages/picasso-forms/src/Rating/Rating.tsx
  packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
  packages/picasso-forms/src/Select/Select.tsx
  packages/picasso-forms/src/Switch/Switch.tsx
  packages/picasso-forms/src/TagSelector/TagSelector.tsx
  packages/picasso-forms/src/TimePicker/TimePicker.tsx
Labels: contribution

#4179 [CT-4540] Export FormField
  .changeset/hot-ravens-smile.md
  packages/picasso/src/index.ts
Labels: contribution

#4170 Increase a timeout for release job
  .github/workflows/release.yml
Labels: no-jira

#4185 Version Packages
  .changeset/tidy-hairs-teach.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#4183 Add TailwindCSS as a peer dependency
  .changeset/polite-files-shake.md
  packages/picasso/package.json
Labels: no-jira

#4186 Version Packages
  .changeset/polite-files-shake.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/topkit-analytics-charts/CHANGELOG.md
  packages/topkit-analytics-charts/package.json
Labels: no-jira

#4190 Version Packages
  .changeset/lemon-bugs-joke.md
  .changeset/serious-goats-attend.md
  packages/base/Backdrop/CHANGELOG.md
  packages/base/Backdrop/package.json
  packages/base/Fade/CHANGELOG.md
  packages/base/Fade/package.json
  packages/picasso-tailwind/CHANGELOG.md
  packages/picasso-tailwind/package.json
Labels: no-jira

#4182 [TOP-4328] Hide submenu on other menu item focus
  .changeset/chilled-feet-buy.md
  packages/base/Menu/src/Menu/hooks/use-drilldown-menu/use-drilldown-menu.ts
Labels: contribution

#4191 Version Packages
  .changeset/chilled-feet-buy.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Menu/CHANGELOG.md
  packages/base/Menu/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4195 Remove github authorization from picasso API calls
  ci/jobs/picasso-kill-temploys/Jenkinsfile
Labels: no-jira

#4187 Update lerna to 8.1.2
  .prettierignore
  nx.json
  package.json
  yarn.lock
Labels: Chore, no-jira

#4188 Fix watch build scripts
  README.md
  nx.json
  package.json
Labels: no-jira

#4196 Move `color` types to regular dependencies
  .changeset/twenty-islands-love.md
  packages/shared/package.json
Labels: no-jira

#4198 Version Packages
  .changeset/sweet-singers-knock.md
  packages/base/EmptyState/CHANGELOG.md
  packages/base/EmptyState/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4207 Version Packages
  .changeset/brave-spies-visit.md
  packages/base/Table/CHANGELOG.md
  packages/base/Table/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4204 Update Cypress Tailwind setup
  .changeset/loud-baboons-approve.md
  .changeset/olive-llamas-retire.md
  .changeset/quiet-cobras-exist.md
  cypress/support/commands.jsx
  packages/base/Carousel/src/CarouselNavigation/CarouselNavigation.tsx
  packages/base/Carousel/src/CarouselNavigation/styles.ts
  packages/base/Page/src/Page/Page.tsx
  packages/base/Page/src/Page/__snapshots__/test.tsx.snap
  packages/base/Page/src/Page/styles.ts
  packages/base/Page/src/PageHamburger/PageHamburger.tsx
  packages/base/Page/src/PageHamburger/styles.ts
  packages/base/Page/src/PageSidebar/styles.ts
  packages/base/Page/src/PageTopBar/__snapshots__/test.tsx.snap
  packages/base/Page/src/PageTopBar/styles.ts
  packages/base/Page/src/PageTopBarMenu/styles.ts
  packages/base/Test-Utils/src/test-utils/TestingPicasso.tsx
  yarn.lock
Labels: no-jira

#4205 [FX-4591] Migrate Button component
  .changeset/pink-ravens-allow-copy.md
  .changeset/pink-ravens-allow.md
  packages/base/Button/package.json
  packages/base/Button/src/Button/Button.tsx
  packages/base/Button/src/Button/__snapshots__/test.tsx.snap
  packages/base/Button/src/Button/styles.ts
  packages/base/Button/src/Button/test.tsx
  packages/base/Button/tsconfig.json
  packages/picasso-tailwind/src/index.js
  yarn.lock
Labels: BREAKING CHANGE

#4212 Fix TableSortableCell DOM nesting in test
  packages/base/Table/src/TableSortableCell/__snapshots__/test.tsx.snap
  packages/base/Table/src/TableSortableCell/test.tsx
Labels: Chore, no-jira

#4208 [CPT-2029] Add support to optional tooltip for query builder fields
  .changeset/polite-boxes-burn.md
  .changeset/unlucky-zebras-do.md
  packages/base/Tooltip/src/Tooltip/Tooltip.tsx
  packages/base/Tooltip/src/Tooltip/story/Offset.example.tsx
  packages/base/Tooltip/src/Tooltip/story/index.jsx
  packages/picasso-query-builder/src/FieldSelector/FieldSelector.tsx
  packages/picasso-query-builder/src/FieldSelector/styles.ts
  packages/picasso-query-builder/src/QueryBuilder/story/FieldDescription.example.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/index.jsx
  packages/picasso-query-builder/src/Select/Select.tsx
  packages/picasso-query-builder/src/utils/generate-select-options.ts
Labels: Feature, contribution
