Repository toptal/picasso, pull requests merged in 2024-07, with the labels that each got.

#4397 Version Packages
  .changeset/clever-horses-cheer.md
  .changeset/fresh-geckos-kick.md
  .changeset/itchy-terms-greet.md
  .changeset/real-avocados-work.md
  .changeset/two-berries-wonder.md
  packages/base/AccountSelect/CHANGELOG.md
  packages/base/AccountSelect/package.json
  packages/base/Alert/CHANGELOG.md
  packages/base/Alert/package.json
  packages/base/Autocomplete/CHANGELOG.md
  packages/base/Autocomplete/package.json
  packages/base/Avatar/CHANGELOG.md
  packages/base/Avatar/package.json
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/base/Calendar/CHANGELOG.md
  packages/base/Calendar/package.json
  packages/base/DatePicker/CHANGELOG.md
  packages/base/DatePicker/package.json
  packages/base/DateSelect/CHANGELOG.md
  packages/base/DateSelect/package.json
  packages/base/Helpbox/CHANGELOG.md
  packages/base/Helpbox/package.json
  packages/base/Menu/CHANGELOG.md
  packages/base/Menu/package.json
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/base/Select/CHANGELOG.md
  packages/base/Select/package.json
  packages/base/Tabs/CHANGELOG.md
  packages/base/Tabs/package.json
  packages/base/Tagselector/CHANGELOG.md
  packages/base/Tagselector/package.json
  packages/base/UserBadge/CHANGELOG.md
  packages/base/UserBadge/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso-rich-text-editor/CHANGELOG.md
  packages/picasso-rich-text-editor/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4408 [TRN-6736] Add Send icon
  .changeset/nine-days-train.md
  packages/base/Icons/src/Icon/Send16.tsx
  packages/base/Icons/src/Icon/Send24.tsx
  packages/base/Icons/src/Icon/SendResponsive.tsx
  packages/base/Icons/src/Icon/index.ts
  packages/base/Icons/src/Icon/svg/send16.svg
  packages/base/Icons/src/Icon/svg/send24.svg
Labels: icon, contribution

#4410 [CRT-7570] Improve `PageHeadMain` to allow using `minHeight`
  .changeset/blue-mails-tan.md
  packages/base/Page/src/PageHead/PageHead.tsx
  packages/base/Page/src/PageHead/story/WithEnabledMinHeight.example.tsx
  packages/base/Page/src/PageHead/story/index.jsx
  packages/base/Page/src/PageHead/styles.ts
Labels: contribution

#4411 Version Packages
  .changeset/blue-mails-tan.md
  packages/base/Page/CHANGELOG.md
  packages/base/Page/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4412 Fix typo in README.md
  packages/picasso/README.md
Labels: no-jira, contribution

#4415 Disable days past maxDate
  .changeset/plenty-singers-design.md
  packages/base/Calendar/src/Calendar/Calendar.tsx
  packages/base/Calendar/src/Calendar/test.tsx
Labels: no-jira

#4422 Version Packages
  .changeset/warm-candles-happen.md
  packages/base/AvatarUpload/CHANGELOG.md
  packages/base/AvatarUpload/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4425 [FX-4698] Fix braces vulnerability
  package.json
  yarn.lock
Labels: dependencies, security

#4424 [FX-5698] Fix tar vulnerability
  yarn.lock
Labels: dependencies, security

#4423 [FX-5698] Fix webpack-dev-middleware vulnerability
  package.json
  yarn.lock
Labels: dependencies, security

#4421 [FX-5698] Fix ip vulnerability
  yarn.lock
Labels: dependencies, security

#4429 Version Packages
  .changeset/calm-cooks-dream.md
  packages/base/Dropzone/CHANGELOG.md
  packages/base/Dropzone/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira
