Repository toptal/picasso, pull requests merged in 2024-01, with the labels that each got.

#4074 [CI-3043] Switch to actions/create-jira-deployment
  .github/workflows/ci.yaml
  .github/workflows/davinci-alpha-package.yml
  .github/workflows/release.yml
Labels: contribution

#4075 [CPT-1478] Add enableResetSearch prop to Select and QB
  .changeset/rare-jokes-build.md
  .changeset/spicy-tips-listen.md
  packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
  packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
  packages/picasso/src/NonNativeSelect/test.tsx
  packages/picasso/src/Select/Select.tsx
  packages/picasso/src/Select/story/SearchBehavior.example.tsx
  packages/picasso/src/SelectBase/hooks/use-select-props/use-search-reset-handler/index.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-search-reset-handler/test.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-search-reset-handler/use-search-reset-handler.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-select-props.ts
  packages/picasso/src/SelectBase/types.ts
Labels: Feature, contribution

#4078 Version Packages
  .changeset/rare-jokes-build.md
  .changeset/spicy-tips-listen.md
  packages/picasso-pictograms/package.json
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4081 Version Packages
  .changeset/strong-moons-clap.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4084 [CPT-1479] Enable select clear button for the qb
  .changeset/few-buckets-knock.md
  packages/picasso-query-builder/package.json
  packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
  packages/picasso-query-builder/src/types/query-builder.ts
Labels: contribution

#4091 Version Packages
  .changeset/few-buckets-knock.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira

#4092 Version Packages
  .changeset/four-chairs-call.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4093 Fix query builder multiselect type
  .changeset/red-weeks-hang.md
  packages/picasso-query-builder/src/types/query-builder.ts
Labels: no-jira, contribution

#4095 Version Packages
  .changeset/ninety-readers-build.md
  packages/picasso-pictograms/package.json
  packages/picasso-provider/CHANGELOG.md
  packages/picasso-provider/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: no-jira

#4102 Version Packages
  .changeset/violet-shoes-rhyme.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4103 Version Packages
  .changeset/dry-insects-wink.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
  packages/picasso-forms/CHANGELOG.md
  packages/picasso-forms/package.json
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4101 [CPT-1480] Prevent multiple Select from closing when search was clicked
  .changeset/friendly-avocados-unite.md
  packages/picasso/src/SelectBase/hooks/use-select-props/use-item-on-click-handler/use-item-on-click-handler.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/test.ts
  packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/use-select-handler.ts
Labels: contribution

#4112 Version Packages
  .changeset/friendly-avocados-unite.md
  packages/picasso-pictograms/package.json
  packages/picasso/CHANGELOG.md
  packages/picasso/package.json
Labels: no-jira

#4113 Version Packages
  .changeset/plenty-foxes-approve.md
  packages/picasso-charts/CHANGELOG.md
  packages/picasso-charts/package.json
Labels: no-jira

#4114 [FX-NULL] Add nx folder to gitignore
  .gitignore
Labels: no-jira

#4118 Transfer query builder ownership
  .github/CODEOWNERS
Labels: no-jira, contribution

#4116 [CPT-1498] Add header property to query builder
  .changeset/chilly-hairs-worry.md
  packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/Header.example.tsx
  packages/picasso-query-builder/src/QueryBuilder/story/index.jsx
  packages/picasso-query-builder/src/types/query-builder.ts
  yarn.lock
Labels: contribution

#4120 Version Packages
  .changeset/chilly-hairs-worry.md
  packages/picasso-query-builder/CHANGELOG.md
  packages/picasso-query-builder/package.json
Labels: no-jira
